<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Chapter 12 Statistical modelling with R | Introduction into R Applications and Programming: A Tutorial</title>
<meta name="author" content="Niël J le Roux and Sugnet Lubbe">
<meta name="description" content="This chapter is an introduction to statistical modelling with R. There are a substantial number of dedicated R modelling packages available. In this chapter only the basics of statistical...">
<meta name="generator" content="bookdown 0.44 with bs4_book()">
<meta property="og:title" content="Chapter 12 Statistical modelling with R | Introduction into R Applications and Programming: A Tutorial">
<meta property="og:type" content="book">
<meta property="og:url" content="https://github.com/sugnet/RTutorial/modelling.html">
<meta property="og:image" content="https://github.com/sugnet/RTutorial/frontcover.jpg">
<meta property="og:description" content="This chapter is an introduction to statistical modelling with R. There are a substantial number of dedicated R modelling packages available. In this chapter only the basics of statistical...">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Chapter 12 Statistical modelling with R | Introduction into R Applications and Programming: A Tutorial">
<meta name="twitter:description" content="This chapter is an introduction to statistical modelling with R. There are a substantial number of dedicated R modelling packages available. In this chapter only the basics of statistical...">
<meta name="twitter:image" content="https://github.com/sugnet/RTutorial/frontcover.jpg">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.9.0/transition.js"></script><script src="libs/bs3compat-0.9.0/tabs.js"></script><script src="libs/bs3compat-0.9.0/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><link href="libs/tabwid-1.1.3/tabwid.css" rel="stylesheet">
<script src="libs/tabwid-1.1.3/tabwid.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS --><style type="text/css">
    
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  </style>
<style type="text/css">
    /* Used with Pandoc 2.11+ new --citeproc when CSL is used */
    div.csl-bib-body { }
    div.csl-entry {
      clear: both;
          margin-bottom: 1em;
        }
    .hanging div.csl-entry {
      margin-left:2em;
      text-indent:-2em;
    }
    div.csl-left-margin {
      min-width:2em;
      float:left;
    }
    div.csl-right-inline {
      margin-left:2em;
      padding-left:1em;
    }
    div.csl-indent {
      margin-left: 2em;
    }
  </style>
<link rel="stylesheet" href="style.css">
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="">Introduction into R Applications and Programming: A Tutorial</a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled"><li><a class="" href="index.html"><span class="header-section-number">Chapter 12</span> Statistical modelling with R</a></li></ul>

        <div class="book-extra">
          <p><a id="book-repo" href="https://github.com/sugnet/RTutorial">View book source <i class="fab fa-github"></i></a></p>
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="modelling" class="section level1" number="12">
<h1>
<span class="header-section-number">12</span> Statistical modelling with R<a class="anchor" aria-label="anchor" href="#modelling"><i class="fas fa-link"></i></a>
</h1>
<p>This chapter is an introduction to statistical modelling with R. There are a substantial number of dedicated R modelling packages available. In this chapter only the basics of statistical modelling with R are considered. However, a thorough understanding of these principles is an invaluable aid in mastering any of the available R packages on statistical modelling and related topics.</p>
<div id="introduction" class="section level2" number="12.1">
<h2>
<span class="header-section-number">12.1</span> Introduction<a class="anchor" aria-label="anchor" href="#introduction"><i class="fas fa-link"></i></a>
</h2>
<p>Some of the aims of statistical modelling are: assessing the relative importance of a set of variables in relation to another variable(s); predicting the value of a dependent variable from those of a set of predictor variables; defining a statistical relationship between the dependent and the independent variables.</p>
<p>Here the following generic functions are considered.</p>
<div class="inline-table"><table class="table table-sm">
<caption>
<span id="tab:ModelFuncs">Table 12.1: </span> Generic modelling functions in R.</caption>
<colgroup>
<col width="22%">
<col width="55%">
<col width="22%">
</colgroup>
<thead><tr class="header">
<th><em><span style="color:#CC99FF">Function</span></em></th>
<th><em><span style="color:#CC99FF">Model</span></em></th>
<th><em><span style="color:#CC99FF">Package</span></em></th>
</tr></thead>
<tbody>
<tr class="odd">
<td><code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code></td>
<td>Linear models</td>
<td><code>stats</code></td>
</tr>
<tr class="even">
<td><code><a href="https://rdrr.io/r/stats/aov.html">aov()</a></code></td>
<td>Analysis of variance</td>
<td><code>stats</code></td>
</tr>
<tr class="odd">
<td><code><a href="https://rdrr.io/r/stats/glm.html">glm()</a></code></td>
<td>Generalized linear models</td>
<td><code>stats</code></td>
</tr>
<tr class="even">
<td><code><a href="https://rdrr.io/pkg/mgcv/man/gam.html">gam()</a></code></td>
<td>Generalized additive models</td>
<td>
<code>gam</code>, <code>mgcv</code>
</td>
</tr>
<tr class="odd">
<td><code><a href="https://rdrr.io/r/stats/loess.html">loess()</a></code></td>
<td>Local regression models</td>
<td><code>stats</code></td>
</tr>
<tr class="even">
<td><code><a href="https://rdrr.io/pkg/rpart/man/rpart.html">rpart()</a></code></td>
<td>Tree-based models</td>
<td><code>rpart</code></td>
</tr>
<tr class="odd">
<td><code><a href="https://rdrr.io/r/stats/nls.html">nls()</a></code></td>
<td>Nonlinear models</td>
<td><code>stats</code></td>
</tr>
</tbody>
</table></div>
</div>
<div id="data-for-statistical-models" class="section level2" number="12.2">
<h2>
<span class="header-section-number">12.2</span> Data for statistical models<a class="anchor" aria-label="anchor" href="#data-for-statistical-models"><i class="fas fa-link"></i></a>
</h2>
<ol style="list-style-type: lower-alpha">
<li><p>Note the difference between <em><span style="color:#FF9966">factors</span></em> (categorical or classification variables), <em><span style="color:#FF9966">regressors</span></em> (continuous or <em><span style="color:#FF9966">numeric</span></em> variables) and frequency data.</p></li>
<li><p>Why must the data be in the form of a dataframe when statistical modelling is carried out with R?</p></li>
<li><p>How are the functions <code><a href="https://rdrr.io/r/base/factor.html">factor()</a></code>, <code><a href="https://rdrr.io/r/base/factor.html">is.factor()</a></code> and <code><a href="https://rdrr.io/r/base/factor.html">is.ordered()</a></code> used to set or determine the class attributes of variables that must behave as factors in further analyses? Note especially the usage of argument <code>'ordered = '</code> of function <code><a href="https://rdrr.io/r/base/factor.html">factor()</a></code>.</p></li>
</ol>
</div>
<div id="expressing-a-statistical-model-in-r" class="section level2" number="12.3">
<h2>
<span class="header-section-number">12.3</span> Expressing a statistical model in R<a class="anchor" aria-label="anchor" href="#expressing-a-statistical-model-in-r"><i class="fas fa-link"></i></a>
</h2>
<ol style="list-style-type: lower-alpha">
<li><p>What role does the tilde-operator (<code>~</code>) play in statistical models in R?</p></li>
<li><p>Study how the operators in Table <a href="modelling.html#tab:ModelOperators">12.2</a> work. These operators have a different meaning when they appear in a statistical model.</p></li>
</ol>
<div class="inline-table"><table class="table table-sm">
<caption>
<span id="tab:ModelOperators">Table 12.2: </span> Operators used in model formulae after the <code>~</code>.</caption>
<colgroup>
<col width="16%">
<col width="41%">
<col width="41%">
</colgroup>
<thead><tr class="header">
<th><em><span style="color:#CC99FF">Operator</span></em></th>
<th><em><span style="color:#CC99FF">Algebraic meaning</span></em></th>
<th><em><span style="color:#CC99FF">Meaning in formula after <code>~</code></span></em></th>
</tr></thead>
<tbody>
<tr class="odd">
<td><code>+</code></td>
<td>Addition</td>
<td>Add a term</td>
</tr>
<tr class="even">
<td><code>-</code></td>
<td>Subtraction</td>
<td>Remove or exclude a term</td>
</tr>
<tr class="odd">
<td><code>*</code></td>
<td>Multiplication</td>
<td>Main effects and interactions</td>
</tr>
<tr class="even">
<td><code>/</code></td>
<td>Division</td>
<td>Main effect and nesting</td>
</tr>
<tr class="odd">
<td><code>:</code></td>
<td>Sequence</td>
<td>Interaction</td>
</tr>
<tr class="even">
<td><code>^</code></td>
<td>Exponentiation</td>
<td>Limit depth of interactions</td>
</tr>
<tr class="odd">
<td><code>%in%</code></td>
<td>Matching</td>
<td>Nesting</td>
</tr>
</tbody>
</table></div>
<ol start="3" style="list-style-type: lower-alpha">
<li><p>In order to ensure that the operators in Table <a href="modelling.html#tab:ModelOperators">12.2</a> have their usual meaning when appearing at the right-hand side of <code>~</code> in a statistical model use the <code><a href="https://rdrr.io/r/base/AsIs.html">I()</a></code> function e.g. <code>I(a+b)</code>.</p></li>
<li><p>Note how <em><span style="color:#FF9966">regression terms</span></em>, <em><span style="color:#FF9966">main effects</span></em>, <em><span style="color:#FF9966">interaction effects</span></em>, <em><span style="color:#FF9966">higher-order interaction effect</span></em>, <em><span style="color:#FF9966">nested effects</span></em> and <em><span style="color:#FF9966">covariate terms</span></em> are specified.</p></li>
<li><p>The following summary illustrates the correspondence between the <em><span style="color:#FF9966">model notation</span></em> of R and the <em><span style="color:#FF9966">algebraic notation</span></em> of models for factors <code>a</code> and <code>b</code> with numeric (continuous) variable <code>x</code>:</p></li>
</ol>
<div class="inline-table"><table class="table table-sm">
<colgroup>
<col width="50%">
<col width="50%">
</colgroup>
<thead><tr class="header">
<th>Model notation</th>
<th>Algebraic notation</th>
</tr></thead>
<tbody>
<tr class="odd">
<td><code>y~a+x</code></td>
<td><span class="math inline">\(y = \mu + \alpha_a + \beta x + \epsilon\)</span></td>
</tr>
<tr class="even">
<td><code>y~a+b+a:b</code></td>
<td><span class="math inline">\(y = \mu + \alpha_a + \beta_b + \gamma_{ab} + \epsilon\)</span></td>
</tr>
<tr class="odd">
<td><code>y~a+a:x</code></td>
<td><span class="math inline">\(y = \mu + \alpha_a + \beta_a x + \epsilon\)</span></td>
</tr>
<tr class="even">
<td><code>y~a*x</code></td>
<td><span class="math inline">\(y = \mu + \alpha_a + \beta x + \gamma_a x + \epsilon\)</span></td>
</tr>
<tr class="odd">
<td><code>y~-1+a/x</code></td>
<td><span class="math inline">\(y = \alpha_a + \beta_a x + \epsilon\)</span></td>
</tr>
</tbody>
</table></div>
<ol start="6" style="list-style-type: lower-alpha">
<li><p>Every numeric variable on the right-hand side of <code>~</code> generates one coefficient to be estimated in a fitted model; each <em><span style="color:#FF9966">level</span></em> of a factor variable generates one coefficient to be estimated in a fitted model. What is an <em><span style="color:#FF9966">estimable function</span></em>?</p></li>
<li><p>Note how transformation of variables can be achieved and how model formulae are stored as R objects of class <em><span style="color:#FF9966">formula</span></em>.</p></li>
</ol>
</div>
<div id="common-arguments-to-r-modelling-functions" class="section level2" number="12.4">
<h2>
<span class="header-section-number">12.4</span> Common arguments to R modelling functions<a class="anchor" aria-label="anchor" href="#common-arguments-to-r-modelling-functions"><i class="fas fa-link"></i></a>
</h2>
<ol style="list-style-type: lower-alpha">
<li><p>The <em><span style="color:#FF9966">formula</span></em> argument. Study how this argument and the period operator work. If a dataframe is specified as an argument to the modelling function a period on the right-hand side of the <code>~</code> indicates that the additive effects of all the variables in the dataframe (except those used at the left-hand side of the <code>~</code>) are included in the model specification.</p></li>
<li><p>The <em><span style="color:#FF9966">data</span></em> argument. Study how this argument works. Note that this argument will accept any R expression that evaluates to a dataframe. Important: if a dataframe is specified in the data argument (i) variables may be referred to by their names; (ii) the dataframe is searched first for a name before the global environment and the rest of the search path; (iii) any other existing object can also be used as a variable.</p></li>
<li><p>The <em><span style="color:#FF9966">subset</span></em> argument. Note how statistical models can be fitted to subsets of data.</p></li>
<li><p>The <em><span style="color:#FF9966">weights</span></em> argument. Study how this argument works especially when iterative procedures are used.</p></li>
<li><p>The <em><span style="color:#FF9966">na.action</span></em> argument. This argument controls how missing values are handled.</p></li>
<li><p>The <em><span style="color:#FF9966">control</span></em> argument. What is the purpose of this argument?</p></li>
</ol>
</div>
<div id="using-the-statistical-modelling-objects" class="section level2" number="12.5">
<h2>
<span class="header-section-number">12.5</span> Using the statistical modelling objects<a class="anchor" aria-label="anchor" href="#using-the-statistical-modelling-objects"><i class="fas fa-link"></i></a>
</h2>
<p><em>Note</em>: each of the modelling functions returns an object whose class attribute has been set to the name of the function e.g. the value of <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> is set to be of class <code>lm</code>. A set of generic functions are available to provide access to the information contained in them.</p>
<p>To see what is available for a particular modelling function use <code>methods (class = function)</code> e.g.</p>
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/methods.html">methods</a></span> <span class="op">(</span>class <span class="op">=</span> <span class="va">lm</span><span class="op">)</span></span>
<span><span class="co">#&gt;  [1] add1           alias          anova         </span></span>
<span><span class="co">#&gt;  [4] case.names     coerce         confint       </span></span>
<span><span class="co">#&gt;  [7] cooks.distance deviance       dfbeta        </span></span>
<span><span class="co">#&gt; [10] dfbetas        drop1          dummy.coef    </span></span>
<span><span class="co">#&gt; [13] effects        extractAIC     family        </span></span>
<span><span class="co">#&gt; [16] formula        hatvalues      influence     </span></span>
<span><span class="co">#&gt; [19] initialize     kappa          labels        </span></span>
<span><span class="co">#&gt; [22] logLik         model.frame    model.matrix  </span></span>
<span><span class="co">#&gt; [25] nobs           plot           predict       </span></span>
<span><span class="co">#&gt; [28] print          proj           qr            </span></span>
<span><span class="co">#&gt; [31] residuals      rstandard      rstudent      </span></span>
<span><span class="co">#&gt; [34] show           simulate       slotsFromS3   </span></span>
<span><span class="co">#&gt; [37] summary        variable.names vcov          </span></span>
<span><span class="co">#&gt; see '?methods' for accessing help and source code</span></span></code></pre></div>
<div class="inline-table"><table class="table table-sm">
<caption>
<span id="tab:ModelObjectFuncs">Table 12.3: </span> Functions for Model Objects.</caption>
<colgroup>
<col width="28%">
<col width="71%">
</colgroup>
<thead><tr class="header">
<th><em><span style="color:#CC99FF">Function</span></em></th>
<th><em><span style="color:#CC99FF">Description</span></em></th>
</tr></thead>
<tbody>
<tr class="odd">
<td><code><a href="https://rdrr.io/r/stats/add1.html">add1()</a></code></td>
<td>Add all possible single terms in a model</td>
</tr>
<tr class="even">
<td><code><a href="https://rdrr.io/r/stats/anova.html">anova()</a></code></td>
<td>Return a sequential analysis of variance table or a comparison of two hierarchical models</td>
</tr>
<tr class="odd">
<td>
<code><a href="https://rdrr.io/r/stats/coef.html">coef()</a></code> or <code><a href="https://rdrr.io/r/stats/coef.html">coefficients()</a></code>
</td>
<td>Extract estimated coefficients</td>
</tr>
<tr class="even">
<td><code><a href="https://rdrr.io/r/stats/deviance.html">deviance()</a></code></td>
<td>Return the deviance</td>
</tr>
<tr class="odd">
<td><code><a href="https://rdrr.io/r/stats/df.residual.html">df.residual()</a></code></td>
<td>Return the residual degrees of freedom</td>
</tr>
<tr class="even">
<td><code><a href="https://rdrr.io/r/stats/add1.html">drop1()</a></code></td>
<td>Drop all possible single terms in a model</td>
</tr>
<tr class="odd">
<td>
<code><a href="https://rdrr.io/r/stats/fitted.values.html">fitted()</a></code> or <code><a href="https://rdrr.io/r/stats/fitted.values.html">fitted.values()</a></code>
</td>
<td>Extract fitted values</td>
</tr>
<tr class="even">
<td><code><a href="https://rdrr.io/r/stats/formula.html">formula()</a></code></td>
<td>Extract the formula on which the model is based</td>
</tr>
<tr class="odd">
<td><code><a href="https://rdrr.io/r/stats/lm.influence.html">influence()</a></code></td>
<td>Extract several types of influence measures</td>
</tr>
<tr class="even">
<td><code><a href="https://rdrr.io/r/graphics/plot.default.html">plot()</a></code></td>
<td>Construct relevant plots</td>
</tr>
<tr class="odd">
<td><code><a href="https://rdrr.io/r/stats/predict.html">predict()</a></code></td>
<td>Calculate predictions (means) optionally with standard errors</td>
</tr>
<tr class="even">
<td><code><a href="https://rdrr.io/r/base/print.html">print()</a></code></td>
<td>Extract information about the analysis</td>
</tr>
<tr class="odd">
<td>
<code><a href="https://rdrr.io/r/stats/residuals.html">resid()</a></code> or <code><a href="https://rdrr.io/r/stats/residuals.html">residuals()</a></code>
</td>
<td>Extract residuals</td>
</tr>
<tr class="even">
<td><code><a href="https://rdrr.io/r/stats/step.html">step()</a></code></td>
<td>Stepwise selection of a model using a AIC criterion</td>
</tr>
<tr class="odd">
<td><code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code></td>
<td>Extract information about the analysis</td>
</tr>
<tr class="even">
<td><code><a href="https://rdrr.io/r/stats/update.html">update()</a></code></td>
<td>Modify and/or refit models</td>
</tr>
</tbody>
</table></div>
<p><em>Note</em>: Do not confuse function <code><a href="https://rdrr.io/r/stats/anova.html">anova()</a></code> which operates on an <code>lm</code> object with function <code><a href="https://rdrr.io/r/stats/aov.html">aov()</a></code> for fitting an analysis of variance model.</p>
<p><em>Recall</em>: Asterisked functions are non-visible. Such functions can be accessed using for example</p>
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/getAnywhere.html">getAnywhere</a></span><span class="op">(</span><span class="va">add1.lm</span><span class="op">)</span></span></code></pre></div>
<ol style="list-style-type: lower-alpha">
<li><p>Note the use of <code><a href="https://rdrr.io/r/base/print.html">print()</a></code>, <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> and <code><a href="https://rdrr.io/r/graphics/plot.default.html">plot()</a></code> to retrieve information about model objects.</p></li>
<li><p>Study the functions that are used to retrieve information about model objects or to modify them as summed up in Table <a href="modelling.html#tab:ModelObjectFuncs">12.3</a>.</p></li>
</ol>
</div>
<div id="usage-of-the-function-with" class="section level2" number="12.6">
<h2>
<span class="header-section-number">12.6</span> Usage of the function <code>with()</code><a class="anchor" aria-label="anchor" href="#usage-of-the-function-with"><i class="fas fa-link"></i></a>
</h2>
<p>Study the help file of function <code><a href="https://rdrr.io/r/base/with.html">with()</a></code> and take note specifically of its usage when calling <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code>.</p>
</div>
<div id="lmAnova" class="section level2" number="12.7">
<h2>
<span class="header-section-number">12.7</span> Linear regression and anova<a class="anchor" aria-label="anchor" href="#lmAnova"><i class="fas fa-link"></i></a>
</h2>
<ol style="list-style-type: lower-alpha">
<li>Consider the <code>Cars93</code> data set available in package <code>MASS</code>. Use the <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> function to perform a regression analysis of <code>MPG.city</code> as a function of a constant term, <code>Length</code>, <code>(Rev.per.mile)</code><span class="math inline">\(^{–1}\)</span>, <code>Weight</code>, <code>RPM</code> and <code>(Horsepower)</code><span class="math inline">\({–1}\)</span>. Note how the function <code><a href="https://rdrr.io/r/stats/update.html">update()</a></code> works. Illustrate the use of the functions <code><a href="https://rdrr.io/r/stats/add1.html">drop1()</a></code> and <code><a href="https://rdrr.io/r/stats/add1.html">add1()</a></code>:</li>
</ol>
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span> <span class="op">(</span><span class="va"><a href="http://www.stats.ox.ac.uk/pub/MASS4/">MASS</a></span><span class="op">)</span></span>
<span><span class="va">lm.city</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span> <span class="op">(</span><span class="va">MPG.city</span> <span class="op">~</span> <span class="fl">1</span><span class="op">+</span> <span class="va">Length</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/base/AsIs.html">I</a></span><span class="op">(</span><span class="fl">1</span><span class="op">/</span><span class="va">Rev.per.mile</span><span class="op">)</span><span class="op">+</span> <span class="va">Weight</span> <span class="op">+</span> <span class="va">RPM</span> <span class="op">+</span></span>
<span>                 <span class="fu"><a href="https://rdrr.io/r/base/AsIs.html">I</a></span><span class="op">(</span><span class="fl">1</span><span class="op">/</span><span class="va">Horsepower</span><span class="op">)</span>, data<span class="op">=</span><span class="va">Cars93</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span> <span class="op">(</span><span class="va">lm.city</span><span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Call:</span></span>
<span><span class="co">#&gt; lm(formula = MPG.city ~ 1 + Length + I(1/Rev.per.mile) + Weight + </span></span>
<span><span class="co">#&gt;     RPM + I(1/Horsepower), data = Cars93)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Residuals:</span></span>
<span><span class="co">#&gt;     Min      1Q  Median      3Q     Max </span></span>
<span><span class="co">#&gt; -5.2344 -1.4863 -0.1570  0.8975 14.0030 </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Coefficients:</span></span>
<span><span class="co">#&gt;                     Estimate Std. Error t value Pr(&gt;|t|)</span></span>
<span><span class="co">#&gt; (Intercept)       -2.913e+00  1.076e+01  -0.271 0.787288</span></span>
<span><span class="co">#&gt; Length             4.115e-02  3.393e-02   1.213 0.228518</span></span>
<span><span class="co">#&gt; I(1/Rev.per.mile)  7.439e+03  4.760e+03   1.563 0.121750</span></span>
<span><span class="co">#&gt; Weight            -3.345e-03  1.221e-03  -2.740 0.007448</span></span>
<span><span class="co">#&gt; RPM                2.750e-03  7.812e-04   3.521 0.000688</span></span>
<span><span class="co">#&gt; I(1/Horsepower)    1.287e+03  2.379e+02   5.410 5.48e-07</span></span>
<span><span class="co">#&gt;                      </span></span>
<span><span class="co">#&gt; (Intercept)          </span></span>
<span><span class="co">#&gt; Length               </span></span>
<span><span class="co">#&gt; I(1/Rev.per.mile)    </span></span>
<span><span class="co">#&gt; Weight            ** </span></span>
<span><span class="co">#&gt; RPM               ***</span></span>
<span><span class="co">#&gt; I(1/Horsepower)   ***</span></span>
<span><span class="co">#&gt; ---</span></span>
<span><span class="co">#&gt; Signif. codes:  </span></span>
<span><span class="co">#&gt; 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Residual standard error: 2.677 on 87 degrees of freedom</span></span>
<span><span class="co">#&gt; Multiple R-squared:  0.7855, Adjusted R-squared:  0.7732 </span></span>
<span><span class="co">#&gt; F-statistic: 63.72 on 5 and 87 DF,  p-value: &lt; 2.2e-16</span></span>
<span><span class="co"># update() is used here to restrict the model fitted in lm.city to cars with </span></span>
<span><span class="co"># front wheel drives</span></span>
<span><span class="va">lm.city.front</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/update.html">update</a></span> <span class="op">(</span><span class="va">lm.city</span>, subset <span class="op">=</span> <span class="va">DriveTrain</span><span class="op">==</span><span class="st">"Front"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span> <span class="op">(</span><span class="va">lm.city.front</span><span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Call:</span></span>
<span><span class="co">#&gt; lm(formula = MPG.city ~ 1 + Length + I(1/Rev.per.mile) + Weight + </span></span>
<span><span class="co">#&gt;     RPM + I(1/Horsepower), data = Cars93, subset = DriveTrain == </span></span>
<span><span class="co">#&gt;     "Front")</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Residuals:</span></span>
<span><span class="co">#&gt;     Min      1Q  Median      3Q     Max </span></span>
<span><span class="co">#&gt; -5.6598 -1.4476  0.0102  0.9468 13.7023 </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Coefficients:</span></span>
<span><span class="co">#&gt;                     Estimate Std. Error t value Pr(&gt;|t|)</span></span>
<span><span class="co">#&gt; (Intercept)        1.599e+00  1.418e+01   0.113 0.910571</span></span>
<span><span class="co">#&gt; Length             2.711e-02  4.875e-02   0.556 0.580093</span></span>
<span><span class="co">#&gt; I(1/Rev.per.mile)  7.895e+03  6.518e+03   1.211 0.230462</span></span>
<span><span class="co">#&gt; Weight            -3.808e-03  1.707e-03  -2.230 0.029406</span></span>
<span><span class="co">#&gt; RPM                2.672e-03  1.016e-03   2.630 0.010784</span></span>
<span><span class="co">#&gt; I(1/Horsepower)    1.246e+03  3.070e+02   4.058 0.000143</span></span>
<span><span class="co">#&gt;                      </span></span>
<span><span class="co">#&gt; (Intercept)          </span></span>
<span><span class="co">#&gt; Length               </span></span>
<span><span class="co">#&gt; I(1/Rev.per.mile)    </span></span>
<span><span class="co">#&gt; Weight            *  </span></span>
<span><span class="co">#&gt; RPM               *  </span></span>
<span><span class="co">#&gt; I(1/Horsepower)   ***</span></span>
<span><span class="co">#&gt; ---</span></span>
<span><span class="co">#&gt; Signif. codes:  </span></span>
<span><span class="co">#&gt; 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Residual standard error: 2.93 on 61 degrees of freedom</span></span>
<span><span class="co">#&gt; Multiple R-squared:  0.7656, Adjusted R-squared:  0.7464 </span></span>
<span><span class="co">#&gt; F-statistic: 39.85 on 5 and 61 DF,  p-value: &lt; 2.2e-16</span></span>
<span></span>
<span><span class="co"># drop1 (lm object, scope) shows the effect of dropping the Length term from </span></span>
<span><span class="co"># the fitted model</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/add1.html">drop1</a></span> <span class="op">(</span><span class="va">lm.city</span>, <span class="va">.</span> <span class="op">~</span> <span class="va">Length</span><span class="op">)</span></span>
<span><span class="co">#&gt; Single term deletions</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Model:</span></span>
<span><span class="co">#&gt; MPG.city ~ 1 + Length + I(1/Rev.per.mile) + Weight + RPM + I(1/Horsepower)</span></span>
<span><span class="co">#&gt;        Df Sum of Sq    RSS    AIC</span></span>
<span><span class="co">#&gt; &lt;none&gt;              623.27 188.92</span></span>
<span><span class="co">#&gt; Length  1    10.536 633.80 188.48</span></span>
<span></span>
<span><span class="co"># Shows the effect of dropping each term in turn from the fitted model </span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/add1.html">drop1</a></span> <span class="op">(</span><span class="va">lm.city</span><span class="op">)</span></span>
<span><span class="co">#&gt; Single term deletions</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Model:</span></span>
<span><span class="co">#&gt; MPG.city ~ 1 + Length + I(1/Rev.per.mile) + Weight + RPM + I(1/Horsepower)</span></span>
<span><span class="co">#&gt;                   Df Sum of Sq    RSS    AIC</span></span>
<span><span class="co">#&gt; &lt;none&gt;                         623.27 188.92</span></span>
<span><span class="co">#&gt; Length             1    10.536 633.80 188.48</span></span>
<span><span class="co">#&gt; I(1/Rev.per.mile)  1    17.495 640.76 189.50</span></span>
<span><span class="co">#&gt; Weight             1    53.796 677.06 194.62</span></span>
<span><span class="co">#&gt; RPM                1    88.801 712.07 199.31</span></span>
<span><span class="co">#&gt; I(1/Horsepower)    1   209.659 832.93 213.89</span></span>
<span></span>
<span><span class="va">lm.city.const</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span> <span class="op">(</span><span class="va">MPG.city</span> <span class="op">~</span> <span class="fl">1</span>, data<span class="op">=</span><span class="va">Cars93</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span> <span class="op">(</span><span class="va">lm.city.const</span><span class="op">)</span></span>
<span><span class="co">#&gt; Analysis of Variance Table</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Response: MPG.city</span></span>
<span><span class="co">#&gt;           Df Sum Sq Mean Sq F value Pr(&gt;F)</span></span>
<span><span class="co">#&gt; Residuals 92 2905.6  31.582</span></span>
<span></span>
<span><span class="co"># add1 (lm object, scope) shows the effect of adding the terms in scope </span></span>
<span><span class="co"># individually in turn to the model in lm object </span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/add1.html">add1</a></span> <span class="op">(</span><span class="va">lm.city.const</span>, <span class="va">.</span> <span class="op">~</span> <span class="va">Length</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/base/AsIs.html">I</a></span><span class="op">(</span><span class="fl">1</span><span class="op">/</span><span class="va">Rev.per.mile</span><span class="op">)</span> <span class="op">+</span> <span class="va">Weight</span> <span class="op">+</span> <span class="va">RPM</span> <span class="op">+</span> </span>
<span>       <span class="fu"><a href="https://rdrr.io/r/base/AsIs.html">I</a></span><span class="op">(</span><span class="fl">1</span><span class="op">/</span><span class="va">Horsepower</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt; Single term additions</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Model:</span></span>
<span><span class="co">#&gt; MPG.city ~ 1</span></span>
<span><span class="co">#&gt;                   Df Sum of Sq     RSS    AIC</span></span>
<span><span class="co">#&gt; &lt;none&gt;                         2905.57 322.09</span></span>
<span><span class="co">#&gt; Length             1   1289.71 1615.86 269.52</span></span>
<span><span class="co">#&gt; I(1/Rev.per.mile)  1   1090.68 1814.89 280.32</span></span>
<span><span class="co">#&gt; Weight             1   2065.52  840.05 208.68</span></span>
<span><span class="co">#&gt; RPM                1    382.96 2522.61 310.94</span></span>
<span><span class="co">#&gt; I(1/Horsepower)    1   1927.30  978.27 222.85</span></span></code></pre></div>
<ol start="2" style="list-style-type: lower-alpha">
<li><p>Is the object <code>a &lt;- as.data.frame(matA)</code> identical with the object <code>a1 &lt;- data.frame(matA)</code>?</p></li>
<li>
<p>Once again, consider the <code>Cars93</code> data set: Consider cars manufactured by Buick, Chevrolet, Oldsmobile and Pontiac. Use the median of <code>Weight</code> to create two car weight groups.</p>
<ul>
<li>Construct an interaction plot to study the interaction between <code>Manufacturer</code> and <code>Weight</code> with respect to the highway fuel consumption. Interpret the graph.</li>
<li>Use the function <code><a href="https://rdrr.io/r/stats/aov.html">aov()</a></code> to perform a two-way anova with highway fuel consumption as dependent variable and as independent (explanatory) variables weight-group and manufacturer.</li>
<li>What do you conclude about the main effects and the interaction effects?</li>
<li>Repeat the above using lm().</li>
</ul>
</li>
<li><p>Study the help file of the <code>whiteside</code> data set available in package <code>MASS</code>. Plot the gas consumption as a function of the temperature. Use different plotting characters and colours for the two levels of the factor variable <code>Insul</code>. Add the regression lines of gas consumption on the temperature for the two levels of <code>Insul</code> to the graph . What do you conclude? Now test for the parallelism of the two regression lines using <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> with terms for <code>Insul</code>, <code>Temp</code> and <code>Insul:Temp</code>. Discuss the results of the analysis.</p></li>
</ol>
</div>
<div id="regression-diagnostics" class="section level2" number="12.8">
<h2>
<span class="header-section-number">12.8</span> Regression diagnostics<a class="anchor" aria-label="anchor" href="#regression-diagnostics"><i class="fas fa-link"></i></a>
</h2>
<ol style="list-style-type: lower-alpha">
<li><p>Study the help file of <code><a href="https://rdrr.io/r/stats/lm.influence.html">lm.influence()</a></code> for information on its return values.</p></li>
<li><p>Standardized residuals as well as jackknife residuals where <span class="math inline">\(stdres = \frac{\hat{e}_i}{s\sqrt{1-h_{ii}}}\)</span> and <span class="math inline">\(studres = \frac{y_i-\hat{y}_{(i)}}{\sqrt{var(y_i-\hat{y}_{(i)})}}\)</span> can be obtained with the help of the following functions: <code><a href="https://rdrr.io/pkg/MASS/man/stdres.html">stdres()</a></code> and <code><a href="https://rdrr.io/pkg/MASS/man/studres.html">studres()</a></code> available in package <code>MASS</code>. Study the help files of these functions.</p></li>
<li><p>Study how <code><a href="https://rdrr.io/r/stats/predict.html">predict()</a></code> and <code><a href="https://rdrr.io/r/stats/fitted.values.html">fitted()</a></code> work.</p></li>
<li><p>Stepwise model selection: study the use of <code><a href="https://rdrr.io/r/stats/step.html">step()</a></code>.</p></li>
<li><p>What is returned by the function <code><a href="https://rdrr.io/r/stats/influence.measures.html">dfbetas()</a></code>?</p></li>
<li><p>Discuss the output of</p></li>
</ol>
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/step.html">step</a></span> <span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span> <span class="op">(</span><span class="va">MPG.highway</span> <span class="op">~</span> <span class="va">Length</span> <span class="op">+</span> <span class="va">Width</span> <span class="op">+</span> <span class="va">Weight</span> <span class="op">+</span> <span class="va">EngineSize</span> <span class="op">+</span> <span class="va">RPM</span> <span class="op">+</span> </span>
<span>            <span class="va">Rev.per.mile</span>, data <span class="op">=</span> <span class="va">Cars93</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt; Start:  AIC=210.55</span></span>
<span><span class="co">#&gt; MPG.highway ~ Length + Width + Weight + EngineSize + RPM + Rev.per.mile</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;                Df Sum of Sq     RSS    AIC</span></span>
<span><span class="co">#&gt; - RPM           1      1.58  771.32 208.74</span></span>
<span><span class="co">#&gt; - EngineSize    1     10.36  780.10 209.79</span></span>
<span><span class="co">#&gt; - Width         1     13.91  783.64 210.22</span></span>
<span><span class="co">#&gt; &lt;none&gt;                       769.74 210.55</span></span>
<span><span class="co">#&gt; - Rev.per.mile  1     17.66  787.39 210.66</span></span>
<span><span class="co">#&gt; - Length        1     50.29  820.02 214.44</span></span>
<span><span class="co">#&gt; - Weight        1    687.78 1457.52 267.93</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Step:  AIC=208.74</span></span>
<span><span class="co">#&gt; MPG.highway ~ Length + Width + Weight + EngineSize + Rev.per.mile</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;                Df Sum of Sq     RSS    AIC</span></span>
<span><span class="co">#&gt; - EngineSize    1      9.19  780.50 207.84</span></span>
<span><span class="co">#&gt; - Width         1     12.56  783.87 208.24</span></span>
<span><span class="co">#&gt; &lt;none&gt;                       771.32 208.74</span></span>
<span><span class="co">#&gt; - Rev.per.mile  1     18.36  789.67 208.93</span></span>
<span><span class="co">#&gt; - Length        1     50.39  821.71 212.63</span></span>
<span><span class="co">#&gt; - Weight        1    699.81 1471.13 266.79</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Step:  AIC=207.84</span></span>
<span><span class="co">#&gt; MPG.highway ~ Length + Width + Weight + Rev.per.mile</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;                Df Sum of Sq     RSS    AIC</span></span>
<span><span class="co">#&gt; - Rev.per.mile  1     10.79  791.29 207.12</span></span>
<span><span class="co">#&gt; &lt;none&gt;                       780.50 207.84</span></span>
<span><span class="co">#&gt; - Width         1     21.50  802.00 208.37</span></span>
<span><span class="co">#&gt; - Length        1     56.14  836.64 212.30</span></span>
<span><span class="co">#&gt; - Weight        1    710.64 1491.14 266.05</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Step:  AIC=207.12</span></span>
<span><span class="co">#&gt; MPG.highway ~ Length + Width + Weight</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;          Df Sum of Sq     RSS    AIC</span></span>
<span><span class="co">#&gt; - Width   1     13.71  805.00 206.72</span></span>
<span><span class="co">#&gt; &lt;none&gt;                 791.29 207.12</span></span>
<span><span class="co">#&gt; - Length  1     52.31  843.61 211.07</span></span>
<span><span class="co">#&gt; - Weight  1    749.41 1540.70 267.09</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Step:  AIC=206.72</span></span>
<span><span class="co">#&gt; MPG.highway ~ Length + Weight</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;          Df Sum of Sq     RSS    AIC</span></span>
<span><span class="co">#&gt; &lt;none&gt;                 805.00 206.72</span></span>
<span><span class="co">#&gt; - Length  1     91.62  896.62 214.74</span></span>
<span><span class="co">#&gt; - Weight  1   1039.48 1844.48 281.82</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Call:</span></span>
<span><span class="co">#&gt; lm(formula = MPG.highway ~ Length + Weight, data = Cars93)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Coefficients:</span></span>
<span><span class="co">#&gt; (Intercept)       Length       Weight  </span></span>
<span><span class="co">#&gt;   37.521781     0.115526    -0.009633</span></span></code></pre></div>
<ol start="7" style="list-style-type: lower-alpha">
<li><p>Calculate and interpret the <code>dfbetas</code> associated with the object <code>lm.city.front</code> created in Section <a href="modelling.html#lmAnova">12.7</a>.</p></li>
<li><p>Continuing (f): obtain a graph with the standardized residuals on the y-axis and the fitted y-values on the x-axis and interpret the graph.</p></li>
<li><p>Continuing (f): obtain a histogram of the studentized residuals. Interpret.</p></li>
<li><p>Consider the object <code>lm.city</code> created in section <a href="modelling.html#lmAnova">12.7</a>. Verify the assumption of normally distributed residuals with the function <code><a href="https://rdrr.io/r/stats/qqnorm.html">qqnorm()</a></code>. See section <a href="graphics2.html#qqplot">11.5</a>.</p></li>
</ol>
</div>
<div id="non-parametric-regression" class="section level2" number="12.9">
<h2>
<span class="header-section-number">12.9</span> Non-parametric regression<a class="anchor" aria-label="anchor" href="#non-parametric-regression"><i class="fas fa-link"></i></a>
</h2>
<ol style="list-style-type: lower-alpha">
<li><p>Inspect the help file of the <code>stackloss</code> data set.</p></li>
<li><p>Execute the following R code:</p></li>
</ol>
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">stack.data</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span> <span class="op">(</span><span class="va">stackloss</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span> <span class="op">(</span><span class="va">stack.data</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"AirFlow"</span>, <span class="st">"WaterTemp"</span>, <span class="st">"AcidConc"</span>, <span class="st">"Loss"</span><span class="op">)</span></span></code></pre></div>
<ol start="3" style="list-style-type: lower-alpha">
<li><p>Describe briefly what is understood by a Local regression model using the help file of the function <code><a href="https://rdrr.io/r/stats/loess.html">loess()</a></code>.</p></li>
<li><p>Execute the following R code:</p></li>
</ol>
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">stack.loess</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/loess.html">loess</a></span><span class="op">(</span><span class="va">Loss</span> <span class="op">~</span> <span class="va">AirFlow</span> <span class="op">*</span> <span class="va">WaterTemp</span>, data <span class="op">=</span> <span class="va">stack.data</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">stack.loess</span><span class="op">)</span></span>
<span><span class="co">#&gt; Call:</span></span>
<span><span class="co">#&gt; loess(formula = Loss ~ AirFlow * WaterTemp, data = stack.data)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Number of Observations: 21 </span></span>
<span><span class="co">#&gt; Equivalent Number of Parameters: 8.86 </span></span>
<span><span class="co">#&gt; Residual Standard Error: 2.986 </span></span>
<span><span class="co">#&gt; Trace of smoother matrix: 10.53  (exact)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Control settings:</span></span>
<span><span class="co">#&gt;   span     :  0.75 </span></span>
<span><span class="co">#&gt;   degree   :  2 </span></span>
<span><span class="co">#&gt;   family   :  gaussian</span></span>
<span><span class="co">#&gt;   surface  :  interpolate      cell = 0.2</span></span>
<span><span class="co">#&gt;   normalize:  TRUE</span></span>
<span><span class="co">#&gt;  parametric:  FALSE FALSE</span></span>
<span><span class="co">#&gt; drop.square:  FALSE FALSE</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">stack.loess</span><span class="op">)</span></span>
<span><span class="co">#&gt;  [1] "n"         "fitted"    "residuals" "enp"      </span></span>
<span><span class="co">#&gt;  [5] "s"         "one.delta" "two.delta" "trace.hat"</span></span>
<span><span class="co">#&gt;  [9] "divisor"   "robust"    "pars"      "kd"       </span></span>
<span><span class="co">#&gt; [13] "call"      "terms"     "xnames"    "x"        </span></span>
<span><span class="co">#&gt; [17] "y"         "weights"</span></span>
<span></span>
<span><span class="va">stack.loess</span><span class="op">$</span><span class="va">x</span></span>
<span><span class="co">#&gt;    AirFlow WaterTemp</span></span>
<span><span class="co">#&gt; 1       80        27</span></span>
<span><span class="co">#&gt; 2       80        27</span></span>
<span><span class="co">#&gt; 3       75        25</span></span>
<span><span class="co">#&gt; 4       62        24</span></span>
<span><span class="co">#&gt; 5       62        22</span></span>
<span><span class="co">#&gt; 6       62        23</span></span>
<span><span class="co">#&gt; 7       62        24</span></span>
<span><span class="co">#&gt; 8       62        24</span></span>
<span><span class="co">#&gt; 9       58        23</span></span>
<span><span class="co">#&gt; 10      58        18</span></span>
<span><span class="co">#&gt; 11      58        18</span></span>
<span><span class="co">#&gt; 12      58        17</span></span>
<span><span class="co">#&gt; 13      58        18</span></span>
<span><span class="co">#&gt; 14      58        19</span></span>
<span><span class="co">#&gt; 15      50        18</span></span>
<span><span class="co">#&gt; 16      50        18</span></span>
<span><span class="co">#&gt; 17      50        19</span></span>
<span><span class="co">#&gt; 18      50        19</span></span>
<span><span class="co">#&gt; 19      50        20</span></span>
<span><span class="co">#&gt; 20      56        20</span></span>
<span><span class="co">#&gt; 21      70        20</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/coplot.html">coplot</a></span> <span class="op">(</span><span class="va">stack.loess</span><span class="op">$</span><span class="va">y</span> <span class="op">~</span> <span class="va">stack.loess</span><span class="op">$</span><span class="va">x</span><span class="op">[</span>,<span class="st">"AirFlow"</span><span class="op">]</span> <span class="op">|</span> <span class="va">stack.loess</span><span class="op">$</span><span class="va">x</span><span class="op">[</span>,<span class="st">"WaterTemp"</span><span class="op">]</span>,</span>
<span>       panel <span class="op">=</span> <span class="va">points</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="11-modelling_files/figure-html/stackloess-1.png" width="672"></div>
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/coplot.html">coplot</a></span> <span class="op">(</span><span class="va">stack.loess</span><span class="op">$</span><span class="va">y</span> <span class="op">~</span> <span class="va">stack.loess</span><span class="op">$</span><span class="va">x</span><span class="op">[</span>,<span class="st">"WaterTemp"</span><span class="op">]</span> <span class="op">|</span> <span class="va">stack.loess</span><span class="op">$</span><span class="va">x</span><span class="op">[</span>,<span class="st">"AirFlow"</span><span class="op">]</span>,</span>
<span>        panel<span class="op">=</span><span class="va">points</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="11-modelling_files/figure-html/stackloess-2.png" width="672"></div>
<p>Comment on the results.</p>
<ol start="5" style="list-style-type: lower-alpha">
<li><p>Alternatively, splines can be used to fit a nonparametric regression model. The package <code>splines</code> provides for fitting B-splines with the <code><a href="https://rdrr.io/r/splines/bs.html">bs()</a></code> function and natural cubic splines with the <code><a href="https://rdrr.io/r/splines/ns.html">ns()</a></code> function.</p></li>
<li><p>Study the help files of the <code><a href="https://rdrr.io/r/splines/bs.html">bs()</a></code> and <code><a href="https://rdrr.io/r/splines/ns.html">ns()</a></code> functions.</p></li>
<li>
<p>Inspect the help file of the <code>ethanol</code> data set available in package <code>lattice</code>.</p>
<ol style="list-style-type: lower-roman">
<li><p>Plot <code>NOx</code> versus <code>E</code>.</p></li>
<li><p>Use <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> and fit a straight line to the data. Add this line to the plot made above. Why is it necessary to order the observations?</p></li>
</ol>
</li>
</ol>
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">y</span> <span class="op">&lt;-</span> <span class="va">ethanol</span><span class="op">$</span><span class="va">NOx</span> <span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/order.html">order</a></span> <span class="op">(</span><span class="va">ethanol</span><span class="op">$</span><span class="va">E</span><span class="op">)</span><span class="op">]</span></span>
<span><span class="va">x</span> <span class="op">&lt;-</span> <span class="va">ethanol</span><span class="op">$</span><span class="va">E</span> <span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/order.html">order</a></span> <span class="op">(</span><span class="va">ethanol</span><span class="op">$</span><span class="va">E</span><span class="op">)</span><span class="op">]</span></span>
<span><span class="va">yhat</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/fitted.values.html">fitted</a></span> <span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span> <span class="op">(</span><span class="va">y</span> <span class="op">~</span> <span class="va">x</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/lines.html">lines</a></span> <span class="op">(</span><span class="va">x</span>, <span class="va">yhat</span>, col <span class="op">=</span> <span class="st">"blue"</span><span class="op">)</span></span></code></pre></div>
<div style="margin-left: 25px; margin-right: 20px;">
<ol start="3" style="list-style-type: lower-roman">
<li>Use <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> and fit a third degree polynomial to the data. Also add this line to the plot in (i).</li>
</ol>
</div>
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">yhat</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/fitted.values.html">fitted</a></span> <span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span> <span class="op">(</span><span class="va">y</span> <span class="op">~</span> <span class="va">x</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/base/AsIs.html">I</a></span><span class="op">(</span><span class="va">x</span><span class="op">^</span><span class="fl">2</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/base/AsIs.html">I</a></span><span class="op">(</span><span class="va">x</span><span class="op">^</span><span class="fl">3</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/lines.html">lines</a></span> <span class="op">(</span><span class="va">x</span>, <span class="va">yhat</span>, col <span class="op">=</span> <span class="st">"magenta"</span><span class="op">)</span></span></code></pre></div>
<div style="margin-left: 25px; margin-right: 20px;">
<ol start="4" style="list-style-type: lower-roman">
<li>Use <code><a href="https://rdrr.io/r/stats/loess.html">loess()</a></code> with a default <code>span = 0.75</code> to fit a local regression function to the data and add this line to the plot.</li>
</ol>
</div>
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">yhat</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/fitted.values.html">fitted</a></span> <span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/loess.html">loess</a></span> <span class="op">(</span><span class="va">y</span> <span class="op">~</span> <span class="va">x</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/lines.html">lines</a></span> <span class="op">(</span><span class="va">x</span>, <span class="va">yhat</span>, col <span class="op">=</span> <span class="st">"green"</span><span class="op">)</span></span></code></pre></div>
<div style="margin-left: 25px; margin-right: 20px;">
<ol start="22" style="list-style-type: lower-alpha">
<li>Use <code><a href="https://rdrr.io/r/splines/bs.html">bs()</a></code> to fit a B-spline with default <code>degree = 3</code> and <code>knots = NULL</code>. Notice that a third degree polynomial is fitted, similar to (iii).</li>
</ol>
</div>
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">yhat</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/fitted.values.html">fitted</a></span> <span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span> <span class="op">(</span><span class="va">y</span> <span class="op">~</span> <span class="fu"><a href="https://rdrr.io/r/splines/bs.html">bs</a></span><span class="op">(</span><span class="va">x</span>, degree<span class="op">=</span><span class="fl">3</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/lines.html">lines</a></span> <span class="op">(</span><span class="va">x</span>, <span class="va">yhat</span>, col <span class="op">=</span> <span class="st">"gold"</span><span class="op">)</span></span></code></pre></div>
<div style="margin-left: 25px; margin-right: 20px;">
<ol start="6" style="list-style-type: lower-roman">
<li>Use <code><a href="https://rdrr.io/r/splines/bs.html">bs()</a></code> to fit a cubic B-spline with 7 degrees of freedom.</li>
</ol>
</div>
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">yhat</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/fitted.values.html">fitted</a></span> <span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span> <span class="op">(</span><span class="va">y</span> <span class="op">~</span> <span class="fu"><a href="https://rdrr.io/r/splines/bs.html">bs</a></span><span class="op">(</span><span class="va">x</span>, df<span class="op">=</span><span class="fl">7</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/lines.html">lines</a></span> <span class="op">(</span><span class="va">x</span>, <span class="va">yhat</span>, col<span class="op">=</span><span class="st">"red"</span><span class="op">)</span></span></code></pre></div>
<div style="margin-left: 25px; margin-right: 20px;">
<ol start="7" style="list-style-type: lower-roman">
<li>Compare the number of knots for the two fits in (v) and (vi).</li>
</ol>
</div>
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/attr.html">attr</a></span> <span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/splines/bs.html">bs</a></span><span class="op">(</span><span class="va">x</span><span class="op">)</span>, <span class="st">"knots"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/attr.html">attr</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/splines/bs.html">bs</a></span><span class="op">(</span><span class="va">x</span><span class="op">)</span>, <span class="st">"Boundary.knots"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/attr.html">attr</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/splines/bs.html">bs</a></span><span class="op">(</span><span class="va">x</span>, df<span class="op">=</span><span class="fl">7</span><span class="op">)</span>, <span class="st">"knots"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/attr.html">attr</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/splines/bs.html">bs</a></span><span class="op">(</span><span class="va">x</span>, df<span class="op">=</span><span class="fl">7</span><span class="op">)</span>, <span class="st">"Boundary.knots"</span><span class="op">)</span></span></code></pre></div>
<div style="margin-left: 25px; margin-right: 20px;">
<ol start="8" style="list-style-type: lower-roman">
<li>Experiment with different values of the span for the <code><a href="https://rdrr.io/r/stats/loess.html">loess()</a></code> function and the <code>df</code> argument of the <code><a href="https://rdrr.io/r/splines/bs.html">bs()</a></code> function.</li>
</ol>
</div>
<ol start="8" style="list-style-type: lower-alpha">
<li>
<p>When producing a coplot (refer to section <a href="graphics2.html#coplot">11.7</a>) it is helpful to draw lines or curves in each of the dependency panels, to make the relationship easier to appreciate. Use the panel argument of <code><a href="https://rdrr.io/r/graphics/coplot.html">coplot()</a></code> to draw in each panel</p>
<ul>
<li>a straight line representing the linear regression between the variables;</li>
<li>a curve representing the polynomial regression;</li>
<li>a spline using <code><a href="https://rdrr.io/r/stats/smooth.spline.html">smooth.spline()</a></code>.</li>
</ul>
</li>
</ol>
<div style="margin-left: 25px; margin-right: 20px;">
<p><em>Hint</em>: Graphical arguments are passed to <code><a href="https://rdrr.io/r/graphics/coplot.html">coplot()</a></code> by writing a suitable panel function as ‘value’ for argument panel of <code><a href="https://rdrr.io/r/graphics/coplot.html">coplot()</a></code>. Study the examples of panel functions below:</p>
</div>
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">panel.straight.line</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">x</span>, <span class="va">y</span>, <span class="va">col</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span><span class="st">"col"</span><span class="op">)</span>, <span class="va">bg</span> <span class="op">=</span> <span class="cn">NA</span>, </span>
<span>                                <span class="va">pch</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span><span class="st">"pch"</span><span class="op">)</span>, <span class="va">cex</span> <span class="op">=</span> <span class="fl">1</span>, <span class="va">col.smooth</span> <span class="op">=</span> <span class="st">"red"</span><span class="op">)</span></span>
<span><span class="op">{</span> <span class="va">datmat</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/cbind.html">cbind</a></span> <span class="op">(</span><span class="va">x</span>, <span class="va">y</span><span class="op">)</span></span>
<span>  <span class="va">datmat</span> <span class="op">&lt;-</span> <span class="va">datmat</span> <span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/order.html">order</a></span> <span class="op">(</span><span class="va">datmat</span><span class="op">[</span>, <span class="fl">1</span><span class="op">]</span><span class="op">)</span>,  <span class="op">]</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/graphics/points.html">points</a></span> <span class="op">(</span><span class="va">datmat</span><span class="op">[</span>, <span class="fl">1</span><span class="op">]</span>, <span class="va">datmat</span><span class="op">[</span>, <span class="fl">2</span><span class="op">]</span>, pch <span class="op">=</span> <span class="va">pch</span>, col <span class="op">=</span> <span class="va">col</span>, bg <span class="op">=</span> <span class="va">bg</span>, cex <span class="op">=</span> <span class="va">cex</span><span class="op">)</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/graphics/lines.html">lines</a></span> <span class="op">(</span><span class="va">datmat</span><span class="op">[</span>, <span class="fl">1</span><span class="op">]</span>, <span class="fu"><a href="https://rdrr.io/r/stats/fitted.values.html">fitted</a></span> <span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span> <span class="op">(</span><span class="va">datmat</span><span class="op">[</span>, <span class="fl">2</span><span class="op">]</span> <span class="op">~</span> <span class="va">datmat</span><span class="op">[</span>, <span class="fl">1</span><span class="op">]</span><span class="op">)</span><span class="op">)</span>, col <span class="op">=</span> <span class="va">col.smooth</span><span class="op">)</span></span>
<span><span class="op">}</span></span>
<span></span>
<span><span class="va">panel.poly</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">x</span>, <span class="va">y</span>, <span class="va">col</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span><span class="st">"col"</span><span class="op">)</span>, <span class="va">bg</span> <span class="op">=</span> <span class="cn">NA</span>, <span class="va">pch</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span><span class="st">"pch"</span><span class="op">)</span>, </span>
<span>                       <span class="va">cex</span> <span class="op">=</span> <span class="fl">1</span>, <span class="va">col.smooth</span> <span class="op">=</span> <span class="st">"red"</span><span class="op">)</span></span>
<span><span class="op">{</span> <span class="va">datmat</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/cbind.html">cbind</a></span><span class="op">(</span><span class="va">x</span>, <span class="va">y</span><span class="op">)</span></span>
<span>  <span class="va">datmat</span> <span class="op">&lt;-</span> <span class="va">datmat</span> <span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/order.html">order</a></span> <span class="op">(</span><span class="va">datmat</span><span class="op">[</span>, <span class="fl">1</span><span class="op">]</span><span class="op">)</span>,  <span class="op">]</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/graphics/points.html">points</a></span> <span class="op">(</span><span class="va">datmat</span><span class="op">[</span>, <span class="fl">1</span><span class="op">]</span>, <span class="va">datmat</span><span class="op">[</span>, <span class="fl">2</span><span class="op">]</span>, pch <span class="op">=</span> <span class="va">pch</span>, col <span class="op">=</span> <span class="va">col</span>, bg <span class="op">=</span> <span class="va">bg</span>, cex <span class="op">=</span> <span class="va">cex</span><span class="op">)</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/graphics/lines.html">lines</a></span> <span class="op">(</span><span class="va">datmat</span><span class="op">[</span>, <span class="fl">1</span><span class="op">]</span>, <span class="fu"><a href="https://rdrr.io/r/stats/fitted.values.html">fitted</a></span> <span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span> <span class="op">(</span><span class="va">datmat</span><span class="op">[</span>, <span class="fl">2</span><span class="op">]</span> <span class="op">~</span> <span class="fu"><a href="https://rdrr.io/r/stats/poly.html">poly</a></span> <span class="op">(</span><span class="va">datmat</span><span class="op">[</span>, <span class="fl">1</span><span class="op">]</span>, <span class="fl">2</span><span class="op">)</span><span class="op">)</span><span class="op">)</span>, </span>
<span>         col <span class="op">=</span> <span class="va">col.smooth</span><span class="op">)</span></span>
<span><span class="op">}</span></span>
<span>               </span>
<span><span class="va">panel.smooth</span> <span class="op">&lt;-</span> <span class="kw">function</span> <span class="op">(</span><span class="va">x</span>, <span class="va">y</span>, <span class="va">col</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span><span class="st">"col"</span><span class="op">)</span>, <span class="va">bg</span> <span class="op">=</span> <span class="cn">NA</span>, <span class="va">pch</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span><span class="st">"pch"</span><span class="op">)</span>, </span>
<span>                          <span class="va">cex</span> <span class="op">=</span> <span class="fl">1</span>, <span class="va">col.smooth</span> <span class="op">=</span> <span class="st">"red"</span>, <span class="va">span</span> <span class="op">=</span> <span class="fl">2</span><span class="op">/</span><span class="fl">3</span>, <span class="va">iter</span> <span class="op">=</span> <span class="fl">3</span>, </span>
<span>                          <span class="va">...</span><span class="op">)</span> </span>
<span><span class="op">{</span> <span class="fu"><a href="https://rdrr.io/r/graphics/points.html">points</a></span><span class="op">(</span><span class="va">x</span>, <span class="va">y</span>, pch <span class="op">=</span> <span class="va">pch</span>, col <span class="op">=</span> <span class="va">col</span>, bg <span class="op">=</span> <span class="va">bg</span>, cex <span class="op">=</span> <span class="va">cex</span><span class="op">)</span></span>
<span>  <span class="va">ok</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/is.finite.html">is.finite</a></span> <span class="op">(</span><span class="va">x</span><span class="op">)</span> <span class="op">&amp;</span> <span class="fu"><a href="https://rdrr.io/r/base/is.finite.html">is.finite</a></span> <span class="op">(</span><span class="va">y</span><span class="op">)</span></span>
<span>  <span class="kw">if</span> <span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/any.html">any</a></span> <span class="op">(</span><span class="va">ok</span><span class="op">)</span><span class="op">)</span> </span>
<span>  <span class="fu"><a href="https://rdrr.io/r/graphics/lines.html">lines</a></span> <span class="op">(</span><span class="fu">stats</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/r/stats/lowess.html">lowess</a></span><span class="op">(</span><span class="va">x</span><span class="op">[</span><span class="va">ok</span><span class="op">]</span>, <span class="va">y</span><span class="op">[</span><span class="va">ok</span><span class="op">]</span>, f <span class="op">=</span> <span class="va">span</span>, iter <span class="op">=</span> <span class="va">iter</span><span class="op">)</span>, </span>
<span>         col <span class="op">=</span> <span class="va">col.smooth</span>, <span class="va">...</span><span class="op">)</span></span>
<span><span class="op">}</span></span></code></pre></div>
<div style="margin-left: 25px; margin-right: 20px;">
<p>An example</p>
</div>
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/coplot.html">coplot</a></span> <span class="op">(</span><span class="va">Illiteracy</span> <span class="op">~</span> <span class="va">Life.Exp</span> <span class="op">|</span> <span class="va">Income</span> <span class="op">*</span> <span class="va">Area</span>, data <span class="op">=</span> <span class="va">state</span>, </span>
<span>        given <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span> <span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/graphics/coplot.html">co.intervals</a></span> <span class="op">(</span><span class="va">state</span><span class="op">$</span><span class="va">Income</span>, <span class="fl">4</span><span class="op">)</span>, </span>
<span>                      <span class="fu"><a href="https://rdrr.io/r/graphics/coplot.html">co.intervals</a></span> <span class="op">(</span><span class="va">state</span><span class="op">$</span><span class="va">Area</span>, <span class="fl">4</span><span class="op">)</span><span class="op">)</span>, </span>
<span>        panel <span class="op">=</span> <span class="va">panel.straight.line</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/coplot.html">coplot</a></span> <span class="op">(</span><span class="va">Illiteracy</span> <span class="op">~</span> <span class="va">Life.Exp</span> <span class="op">|</span> <span class="va">Income</span> <span class="op">*</span> <span class="va">Area</span>, data <span class="op">=</span> <span class="va">state</span>, </span>
<span>        given <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span> <span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/graphics/coplot.html">co.intervals</a></span> <span class="op">(</span><span class="va">state</span><span class="op">$</span><span class="va">Income</span>, <span class="fl">4</span><span class="op">)</span>, </span>
<span>                      <span class="fu"><a href="https://rdrr.io/r/graphics/coplot.html">co.intervals</a></span> <span class="op">(</span><span class="va">state</span><span class="op">$</span><span class="va">Area</span>, <span class="fl">4</span><span class="op">)</span><span class="op">)</span>, </span>
<span>        panel <span class="op">=</span> <span class="va">panel.poly</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/coplot.html">coplot</a></span> <span class="op">(</span><span class="va">Illiteracy</span> <span class="op">~</span> <span class="va">Life.Exp</span> <span class="op">|</span> <span class="va">Income</span> <span class="op">*</span> <span class="va">Area</span>, data <span class="op">=</span> <span class="va">state</span>, </span>
<span>        given <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span> <span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/graphics/coplot.html">co.intervals</a></span> <span class="op">(</span><span class="va">state</span><span class="op">$</span><span class="va">Income</span>, <span class="fl">4</span><span class="op">)</span>, </span>
<span>                      <span class="fu"><a href="https://rdrr.io/r/graphics/coplot.html">co.intervals</a></span> <span class="op">(</span><span class="va">state</span><span class="op">$</span><span class="va">Area</span>, <span class="fl">4</span><span class="op">)</span><span class="op">)</span>, </span>
<span>        panel <span class="op">=</span> <span class="va">panel.smooth</span><span class="op">)</span></span></code></pre></div>
</div>
<div id="the-function-glm" class="section level2" number="12.10">
<h2>
<span class="header-section-number">12.10</span> The function glm()<a class="anchor" aria-label="anchor" href="#the-function-glm"><i class="fas fa-link"></i></a>
</h2>
<p>Consider the following data frame treatments</p>
<div class="inline-table"><table class="table table-sm">
<colgroup>
<col width="33%">
<col width="33%">
<col width="33%">
</colgroup>
<thead><tr class="header">
<th><em><span style="color:#CC99FF">TreatA</span></em></th>
<th><em><span style="color:#CC99FF">TreatB</span></em></th>
<th><em><span style="color:#CC99FF">Counts</span></em></th>
</tr></thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>1</td>
<td>18</td>
</tr>
<tr class="even">
<td>1</td>
<td>2</td>
<td>17</td>
</tr>
<tr class="odd">
<td>1</td>
<td>3</td>
<td>15</td>
</tr>
<tr class="even">
<td>2</td>
<td>1</td>
<td>20</td>
</tr>
<tr class="odd">
<td>2</td>
<td>2</td>
<td>10</td>
</tr>
<tr class="even">
<td>2</td>
<td>3</td>
<td>20</td>
</tr>
<tr class="odd">
<td>3</td>
<td>1</td>
<td>25</td>
</tr>
<tr class="even">
<td>3</td>
<td>2</td>
<td>13</td>
</tr>
<tr class="odd">
<td>3</td>
<td>3</td>
<td>12</td>
</tr>
</tbody>
</table></div>
<p>Why is a two-way anova not appropriate here?</p>
<p>GLM extends the linear model in two ways: (a) the expected value is replaced by a <em><span style="color:#FF9966">function</span></em> of the expected value, called the link function and (b) the assumption of observations from a Gaussian distribution is extended to include other distributions from the exponential family of probability distributions.</p>
<p>Use <code><a href="https://rdrr.io/r/stats/glm.html">glm()</a></code> with <code>family = poisson()</code> to fit the following generalized linear models to the data: <code>Counts ~ TreatA + TreatB</code> and <code>Counts ~ TreatA * TreatB</code>.</p>
<p>What are your conclusions?</p>
</div>
<div id="the-function-gam" class="section level2" number="12.11">
<h2>
<span class="header-section-number">12.11</span> The function gam()<a class="anchor" aria-label="anchor" href="#the-function-gam"><i class="fas fa-link"></i></a>
</h2>
<ol style="list-style-type: lower-alpha">
<li>Describe briefly what is understood by a <em><span style="color:#FF9966">generalized additive model</span></em>.</li>
</ol>
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span> <span class="op">(</span><span class="va">gam</span><span class="op">)</span> </span>
<span><span class="va">stack.gam</span> <span class="op">&lt;-</span> <span class="fu">gam</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/gam/man/gam.html">gam</a></span> <span class="op">(</span><span class="va">Loss</span> <span class="op">~</span> <span class="fu"><a href="https://rdrr.io/pkg/gam/man/gam.s.html">s</a></span><span class="op">(</span><span class="va">AirFlow</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/pkg/gam/man/gam.s.html">s</a></span><span class="op">(</span><span class="va">WaterTemp</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/pkg/gam/man/gam.s.html">s</a></span><span class="op">(</span><span class="va">AcidConc</span><span class="op">)</span>,</span>
<span>                       control <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/gam/man/gam.control.html">gam.control</a></span> <span class="op">(</span>bf.maxit <span class="op">=</span> <span class="fl">50</span><span class="op">)</span>, data <span class="op">=</span> <span class="va">stack.data</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">stack.gam</span><span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Call: gam::gam(formula = Loss ~ s(AirFlow) + s(WaterTemp) + s(AcidConc), </span></span>
<span><span class="co">#&gt;     data = stack.data, control = gam.control(bf.maxit = 50))</span></span>
<span><span class="co">#&gt; Deviance Residuals:</span></span>
<span><span class="co">#&gt;     Min      1Q  Median      3Q     Max </span></span>
<span><span class="co">#&gt; -3.0831 -1.6186  0.2447  0.8839  3.9253 </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; (Dispersion Parameter for gaussian family taken to be 8.4463)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;     Null Deviance: 2069.238 on 20 degrees of freedom</span></span>
<span><span class="co">#&gt; Residual Deviance: 67.5711 on 8.0001 degrees of freedom</span></span>
<span><span class="co">#&gt; AIC: 112.1371 </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Number of Local Scoring Iterations: NA </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Anova for Parametric Effects</span></span>
<span><span class="co">#&gt;                  Df  Sum Sq Mean Sq  F value    Pr(&gt;F)    </span></span>
<span><span class="co">#&gt; s(AirFlow)   1.0000 1435.95 1435.95 170.0095 1.136e-06 ***</span></span>
<span><span class="co">#&gt; s(WaterTemp) 1.0000  272.77  272.77  32.2944 0.0004635 ***</span></span>
<span><span class="co">#&gt; s(AcidConc)  1.0000    8.23    8.23   0.9742 0.3525476    </span></span>
<span><span class="co">#&gt; Residuals    8.0001   67.57    8.45                       </span></span>
<span><span class="co">#&gt; ---</span></span>
<span><span class="co">#&gt; Signif. codes:  </span></span>
<span><span class="co">#&gt; 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Anova for Nonparametric Effects</span></span>
<span><span class="co">#&gt;              Npar Df Npar F   Pr(F)  </span></span>
<span><span class="co">#&gt; (Intercept)                          </span></span>
<span><span class="co">#&gt; s(AirFlow)         3 1.0050 0.43916  </span></span>
<span><span class="co">#&gt; s(WaterTemp)       3 3.3321 0.07703 .</span></span>
<span><span class="co">#&gt; s(AcidConc)        3 0.9953 0.44293  </span></span>
<span><span class="co">#&gt; ---</span></span>
<span><span class="co">#&gt; Signif. codes:  </span></span>
<span><span class="co">#&gt; 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span>mfrow<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">3</span>,<span class="fl">1</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">stack.gam</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="11-modelling_files/figure-html/gam-1.png" width="672"></div>
<div style="margin-left: 25px; margin-right: 20px;">
<p>Comment on the results.</p>
</div>
<ol start="2" style="list-style-type: lower-alpha">
<li>
<p>Return to the <code>ethanol</code> data set available in package <code>lattice</code>.</p>
<ol style="list-style-type: lower-roman">
<li>Use <code><a href="https://rdrr.io/pkg/mgcv/man/gam.html">gam()</a></code> in package <code>mgcv</code> and fit a B-spline to the data. The following code can be used for that:</li>
</ol>
</li>
</ol>
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/detach.html">detach</a></span> <span class="op">(</span><span class="st">'package:gam'</span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span> <span class="op">(</span><span class="va">mgcv</span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span> <span class="op">(</span><span class="va"><a href="https://lattice.r-forge.r-project.org/">lattice</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span> <span class="op">(</span><span class="va">splines</span><span class="op">)</span></span>
<span></span>
<span><span class="va">out</span> <span class="op">&lt;-</span> <span class="fu">mgcv</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/mgcv/man/gam.html">gam</a></span> <span class="op">(</span><span class="va">NOx</span> <span class="op">~</span> <span class="fu"><a href="https://rdrr.io/r/splines/bs.html">bs</a></span><span class="op">(</span><span class="va">E</span>, df <span class="op">=</span> <span class="fl">7</span><span class="op">)</span>, data <span class="op">=</span> <span class="va">ethanol</span><span class="op">)</span></span>
<span><span class="co"># str(out)    # inspect output components</span></span>
<span></span>
<span><span class="co"># data must be sorted according to E values</span></span>
<span><span class="va">data.temp</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span> <span class="op">(</span><span class="va">ethanol</span> <span class="op">[</span>,<span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>,<span class="fl">3</span><span class="op">)</span><span class="op">]</span>, fitted <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/fitted.values.html">fitted</a></span><span class="op">(</span><span class="va">out</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">data.ordered</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/with.html">with</a></span> <span class="op">(</span><span class="va">data.temp</span>, <span class="va">data.temp</span> <span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/order.html">order</a></span><span class="op">(</span><span class="va">E</span><span class="op">)</span>,<span class="op">]</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/with.html">with</a></span> <span class="op">(</span><span class="va">data.ordered</span>, <span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span> <span class="op">(</span>x <span class="op">=</span> <span class="va">E</span>, y <span class="op">=</span> <span class="va">NOx</span>, pch <span class="op">=</span> <span class="fl">15</span>, col <span class="op">=</span> <span class="st">'blue'</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/with.html">with</a></span> <span class="op">(</span><span class="va">data.ordered</span>, <span class="fu"><a href="https://rdrr.io/r/graphics/lines.html">lines</a></span> <span class="op">(</span>x <span class="op">=</span> <span class="va">E</span>, y <span class="op">=</span> <span class="va">fitted</span>, col <span class="op">=</span> <span class="st">'red'</span>, lwd <span class="op">=</span> <span class="fl">2</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="11-modelling_files/figure-html/mgcv_gam-1.png" width="672"></div>
<div style="margin-left: 45px; margin-right: 20px;">
<p>The domain of the predictor is divided by knots and a B-spline generates a set of piecewise polynomials restricted to be continuous at the knots. Execute the following command:</p>
</div>
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span> <span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/range.html">range</a></span> <span class="op">(</span><span class="va">ethanol</span><span class="op">$</span><span class="va">E</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>,<span class="fl">1</span><span class="op">)</span>, type <span class="op">=</span> <span class="st">"n"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/apply.html">apply</a></span> <span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/splines/bs.html">bs</a></span> <span class="op">(</span><span class="va">ethanol</span><span class="op">$</span><span class="va">E</span>, df <span class="op">=</span> <span class="fl">7</span><span class="op">)</span>, <span class="fl">2</span>, <span class="kw">function</span><span class="op">(</span><span class="va">y</span>, <span class="va">x</span><span class="op">)</span></span>
<span>                              <span class="fu"><a href="https://rdrr.io/r/graphics/lines.html">lines</a></span> <span class="op">(</span><span class="va">x</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/order.html">order</a></span><span class="op">(</span><span class="va">x</span><span class="op">)</span><span class="op">]</span>, <span class="va">y</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/order.html">order</a></span><span class="op">(</span><span class="va">x</span><span class="op">)</span><span class="op">]</span><span class="op">)</span>, x <span class="op">=</span> <span class="va">ethanol</span><span class="op">$</span><span class="va">E</span><span class="op">)</span></span>
<span><span class="co">#&gt; NULL</span></span>
<span><span class="va">knot.vec</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/attr.html">attr</a></span> <span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/splines/bs.html">bs</a></span> <span class="op">(</span><span class="va">ethanol</span><span class="op">$</span><span class="va">E</span> <span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/order.html">order</a></span> <span class="op">(</span><span class="va">ethanol</span><span class="op">$</span><span class="va">E</span><span class="op">)</span><span class="op">]</span>, df <span class="op">=</span> <span class="fl">7</span><span class="op">)</span>, <span class="st">"knots"</span><span class="op">)</span></span>
<span><span class="kw">for</span> <span class="op">(</span><span class="va">i</span> <span class="kw">in</span> <span class="va">knot.vec</span><span class="op">)</span> <span class="fu"><a href="https://rdrr.io/r/graphics/lines.html">lines</a></span> <span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="va">i</span>,<span class="fl">2</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>,<span class="fl">1</span><span class="op">)</span>, lty <span class="op">=</span> <span class="fl">2</span><span class="op">)</span></span></code></pre></div>
<div class="figure">
<span style="display:block;" id="fig:knots"></span>
<img src="11-modelling_files/figure-html/knots-1.png" alt="Cubic B-spline basis functions with 4 interior knots." width="100%"><p class="caption">
Figure 12.1: Cubic B-spline basis functions with 4 interior knots.
</p>
</div>
<div style="margin-left: 45px; margin-right: 20px;">
<p>A set of <span class="math inline">\(7\)</span> basis functions were generated, each a degree <span class="math inline">\(3\)</span> polynomial in an interval with
<span class="math inline">\(7 - 3 = 4\)</span> interior knots. Experiment with specifying either a different degree for the polynomials, or different numbers of knots. The specific knots can also be specified, e.g. <code>bs (ethanol$E, knots = c (0.7, 0.9, 1.1))</code>.</p>
</div>
<div style="margin-left: 25px; margin-right: 20px;">
<ol start="2" style="list-style-type: lower-roman">
<li><p>It has been shown that B-splines can exhibit erratic behavior beyond the boundary knots. Repeat the fits and plots above, replacing the B-splines with natural cubic splines with the function <code><a href="https://rdrr.io/r/splines/ns.html">ns()</a></code>. Natural cubic splines constrain the basis functions to be linear beyond the boundary knots. As a result, a natural cubic spline with <span class="math inline">\(K\)</span> knots is represented by <span class="math inline">\(K\)</span> basis functions.</p></li>
<li><p>Selecting the position and number of knots can be subjective. Smoothing splines solves the knot selection problem by making each observation a knot and controlling the overfitting with a single penalty parameter. Repeat the fits and plots in (i), replacing the B-splines with smoothing splines with the function <code><a href="https://rdrr.io/pkg/mgcv/man/s.html">s()</a></code>, similar to the fit in (a).</p></li>
</ol>
</div>
</div>
<div id="the-function-rpart" class="section level2" number="12.12">
<h2>
<span class="header-section-number">12.12</span> The function rpart()<a class="anchor" aria-label="anchor" href="#the-function-rpart"><i class="fas fa-link"></i></a>
</h2>
<ol style="list-style-type: lower-alpha">
<li><p>Describe briefly what is understood by <em><span style="color:#FF9966">Regression and Classification Trees</span></em> using the help file of the function <code><a href="https://rdrr.io/pkg/rpart/man/rpart.html">rpart()</a></code> in package <code>rpart</code>.</p></li>
<li><p>Study the help file of the <code>kyphosis</code> data set available in package <code>MASS</code>.</p></li>
<li><p>Execute the following R code:</p></li>
</ol>
<div class="sourceCode" id="cb19"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span> <span class="op">(</span><span class="va"><a href="https://github.com/bethatkinson/rpart">rpart</a></span><span class="op">)</span></span>
<span><span class="va">fit</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/rpart/man/rpart.html">rpart</a></span><span class="op">(</span><span class="va">Kyphosis</span> <span class="op">~</span> <span class="va">Age</span> <span class="op">+</span> <span class="va">Number</span> <span class="op">+</span> <span class="va">Start</span>, data<span class="op">=</span><span class="va">kyphosis</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">fit</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/text.html">text</a></span><span class="op">(</span><span class="va">fit</span>, use.n <span class="op">=</span> <span class="cn">TRUE</span>, xpd <span class="op">=</span> <span class="cn">NA</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="11-modelling_files/figure-html/rpart-1.png" width="672"></div>
<p>Comment on the results.</p>
<ol start="4" style="list-style-type: lower-alpha">
<li>The package <code>partykit()</code> provides a toolkit for recursive partitioning. A more informative tree diagram compared to (c) can be obtained with the code:</li>
</ol>
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span> <span class="op">(</span><span class="va"><a href="http://partykit.r-forge.r-project.org/partykit/">partykit</a></span><span class="op">)</span></span>
<span><span class="va">fit2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/partykit/man/party-coercion.html">as.party</a></span><span class="op">(</span><span class="va">fit</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">fit2</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="11-modelling_files/figure-html/partykit-1.png" width="672"></div>
</div>
<div id="nonlinear-regression-and-the-function-nls" class="section level2" number="12.13">
<h2>
<span class="header-section-number">12.13</span> Nonlinear regression and the function nls()<a class="anchor" aria-label="anchor" href="#nonlinear-regression-and-the-function-nls"><i class="fas fa-link"></i></a>
</h2>
<p>The asymptotic regression model has the form:</p>
<p><span class="math display">\[
y = \alpha + \beta e^{\gamma x}.
\]</span></p>
<p>When <span class="math inline">\(\alpha &gt; 0\)</span>, <span class="math inline">\(\beta &lt; 0\)</span> and <span class="math inline">\(\gamma &lt; 0\)</span> the above model becomes Mistcherlich’s model of the law of diminishing returns. According to the law of diminishing returns the yield, <span class="math inline">\(y\)</span>, initially increases quickly with increasing values of <span class="math inline">\(x\)</span>, but then the yield slows down and finally levels off just below the value of <span class="math inline">\(\alpha\)</span>. The parameters <span class="math inline">\(\alpha &gt; 0\)</span>, <span class="math inline">\(\beta &lt; 0\)</span> and <span class="math inline">\(\gamma &lt; 0\)</span> have the following meaning:</p>
<div style="margin-left: 25px; margin-right: 20px;">
<ul>
<li><p><span class="math inline">\(\alpha\)</span> represents the upper asymptote for yield</p></li>
<li><p><span class="math inline">\(\beta\)</span> is the difference between the value of <span class="math inline">\(y\)</span> when <span class="math inline">\(x = 0\)</span> and the upper asymptote</p></li>
</ul>
</div>
<p>The asymptotic regression model may be reparameterized such that <span class="math inline">\(\beta\)</span> is replaced by <span class="math inline">\(\delta - \alpha\)</span> where <span class="math inline">\(\delta\)</span> represents the yield when <span class="math inline">\(x = 0\)</span>. A special case of the asymptotic regression model occurs when <span class="math inline">\(\delta = 0\)</span>:</p>
<p><span class="math display">\[
y = \alpha - \alpha e^{\gamma x} = \alpha (1 - e^{\gamma x}).
\]</span></p>
<p>The asymptotic regression model represents a nonlinear regression model and in general no closed form solution exists for estimating its parameters. The R function <code><a href="https://rdrr.io/r/stats/nls.html">nls()</a></code> can be used to estimate the parameters of the model. When function <code><a href="https://rdrr.io/r/stats/nls.html">nls()</a></code> is employed starting values for the iterative estimating procedure are necessary.</p>
<div id="choosing-starting-values" class="section level3" number="12.13.1">
<h3>
<span class="header-section-number">12.13.1</span> Choosing starting values<a class="anchor" aria-label="anchor" href="#choosing-starting-values"><i class="fas fa-link"></i></a>
</h3>
<ol style="list-style-type: decimal">
<li><p>A starting value for can be found by looking at a scatterplot of <span class="math inline">\(y\)</span> as a function of <span class="math inline">\(x\)</span> and then chooses as starting value just larger than the largest value of <span class="math inline">\(y\)</span>.</p></li>
<li><p>is the difference between the value of <span class="math inline">\(y\)</span> when <span class="math inline">\(x = 0\)</span> and the upper asymptote. A reasonable starting value is the minimum value of <span class="math inline">\(y - \alpha\)</span>.</p></li>
<li><p>can be roughly initially estimated by the negative of the slope between two “well separated” points on the plot.</p></li>
</ol>
<ol style="list-style-type: lower-alpha">
<li><p>Study the help file of <code><a href="https://rdrr.io/r/stats/nls.html">nls()</a></code>. Notice carefully how <code><a href="https://rdrr.io/r/stats/nls.html">nls()</a></code> is called.</p></li>
<li><p>The data below is the <code>Yield</code> of a product after a chemical treatment of different time duration. Three replicates were made at each treatment time.</p></li>
</ol>
<div class="tabwid">
<style>.cl-7d6dc08e{}.cl-7d5ff09e{font-family:'Arial';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(102, 102, 102, 1.00);background-color:transparent;}.cl-7d65fd2c{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:3pt;padding-top:3pt;padding-left:3pt;padding-right:3pt;line-height: 1;background-color:transparent;}.cl-7d65fd40{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:3pt;padding-top:3pt;padding-left:3pt;padding-right:3pt;line-height: 1;background-color:transparent;}.cl-7d6627a2{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7d6627ac{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style>
<div class="inline-table"><table data-quarto-disable-processing="true" class="cl-7d6dc08e">
<thead><tr style="overflow-wrap:break-word;">
<th class="cl-7d6627a2"><p class="cl-7d65fd2c"><span class="cl-7d5ff09e">Time (Hrs)</span></p></th>
<th class="cl-7d6627a2"><p class="cl-7d65fd2c"><span class="cl-7d5ff09e">Rep1</span></p></th>
<th class="cl-7d6627a2"><p class="cl-7d65fd2c"><span class="cl-7d5ff09e">Rep2</span></p></th>
<th class="cl-7d6627a2"><p class="cl-7d65fd2c"><span class="cl-7d5ff09e">Rep3</span></p></th>
</tr></thead>
<tbody>
<tr style="overflow-wrap:break-word;">
<td class="cl-7d6627ac"><p class="cl-7d65fd40"><span class="cl-7d5ff09e">0</span></p></td>
<td class="cl-7d6627ac"><p class="cl-7d65fd40"><span class="cl-7d5ff09e">0.0000</span></p></td>
<td class="cl-7d6627ac"><p class="cl-7d65fd40"><span class="cl-7d5ff09e">0.0000</span></p></td>
<td class="cl-7d6627ac"><p class="cl-7d65fd40"><span class="cl-7d5ff09e">0.0000</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-7d6627ac"><p class="cl-7d65fd40"><span class="cl-7d5ff09e">3</span></p></td>
<td class="cl-7d6627ac"><p class="cl-7d65fd40"><span class="cl-7d5ff09e">0.0846</span></p></td>
<td class="cl-7d6627ac"><p class="cl-7d65fd40"><span class="cl-7d5ff09e">0.0556</span></p></td>
<td class="cl-7d6627ac"><p class="cl-7d65fd40"><span class="cl-7d5ff09e">0.0501</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-7d6627ac"><p class="cl-7d65fd40"><span class="cl-7d5ff09e">6</span></p></td>
<td class="cl-7d6627ac"><p class="cl-7d65fd40"><span class="cl-7d5ff09e">0.1072</span></p></td>
<td class="cl-7d6627ac"><p class="cl-7d65fd40"><span class="cl-7d5ff09e">0.0604</span></p></td>
<td class="cl-7d6627ac"><p class="cl-7d65fd40"><span class="cl-7d5ff09e">0.0545</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-7d6627ac"><p class="cl-7d65fd40"><span class="cl-7d5ff09e">12</span></p></td>
<td class="cl-7d6627ac"><p class="cl-7d65fd40"><span class="cl-7d5ff09e">0.1255</span></p></td>
<td class="cl-7d6627ac"><p class="cl-7d65fd40"><span class="cl-7d5ff09e">0.0590</span></p></td>
<td class="cl-7d6627ac"><p class="cl-7d65fd40"><span class="cl-7d5ff09e">0.0705</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-7d6627ac"><p class="cl-7d65fd40"><span class="cl-7d5ff09e">18</span></p></td>
<td class="cl-7d6627ac"><p class="cl-7d65fd40"><span class="cl-7d5ff09e">0.1671</span></p></td>
<td class="cl-7d6627ac"><p class="cl-7d65fd40"><span class="cl-7d5ff09e">0.0799</span></p></td>
<td class="cl-7d6627ac"><p class="cl-7d65fd40"><span class="cl-7d5ff09e">0.0687</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-7d6627ac"><p class="cl-7d65fd40"><span class="cl-7d5ff09e">24</span></p></td>
<td class="cl-7d6627ac"><p class="cl-7d65fd40"><span class="cl-7d5ff09e">0.1988</span></p></td>
<td class="cl-7d6627ac"><p class="cl-7d65fd40"><span class="cl-7d5ff09e">0.0958</span></p></td>
<td class="cl-7d6627ac"><p class="cl-7d65fd40"><span class="cl-7d5ff09e">0.0655</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-7d6627ac"><p class="cl-7d65fd40"><span class="cl-7d5ff09e">48</span></p></td>
<td class="cl-7d6627ac"><p class="cl-7d65fd40"><span class="cl-7d5ff09e">0.2927</span></p></td>
<td class="cl-7d6627ac"><p class="cl-7d65fd40"><span class="cl-7d5ff09e">0.1739</span></p></td>
<td class="cl-7d6627ac"><p class="cl-7d65fd40"><span class="cl-7d5ff09e">0.1075</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-7d6627ac"><p class="cl-7d65fd40"><span class="cl-7d5ff09e">72</span></p></td>
<td class="cl-7d6627ac"><p class="cl-7d65fd40"><span class="cl-7d5ff09e">0.3713</span></p></td>
<td class="cl-7d6627ac"><p class="cl-7d65fd40"><span class="cl-7d5ff09e">0.1910</span></p></td>
<td class="cl-7d6627ac"><p class="cl-7d65fd40"><span class="cl-7d5ff09e">0.1418</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-7d6627ac"><p class="cl-7d65fd40"><span class="cl-7d5ff09e">96</span></p></td>
<td class="cl-7d6627ac"><p class="cl-7d65fd40"><span class="cl-7d5ff09e">0.4773</span></p></td>
<td class="cl-7d6627ac"><p class="cl-7d65fd40"><span class="cl-7d5ff09e">0.2669</span></p></td>
<td class="cl-7d6627ac"><p class="cl-7d65fd40"><span class="cl-7d5ff09e">0.1725</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-7d6627ac"><p class="cl-7d65fd40"><span class="cl-7d5ff09e">168</span></p></td>
<td class="cl-7d6627ac"><p class="cl-7d65fd40"><span class="cl-7d5ff09e">0.6158</span></p></td>
<td class="cl-7d6627ac"><p class="cl-7d65fd40"><span class="cl-7d5ff09e">0.3584</span></p></td>
<td class="cl-7d6627ac"><p class="cl-7d65fd40"><span class="cl-7d5ff09e">0.3224</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-7d6627ac"><p class="cl-7d65fd40"><span class="cl-7d5ff09e">336</span></p></td>
<td class="cl-7d6627ac"><p class="cl-7d65fd40"><span class="cl-7d5ff09e">0.7297</span></p></td>
<td class="cl-7d6627ac"><p class="cl-7d65fd40"><span class="cl-7d5ff09e">0.4339</span></p></td>
<td class="cl-7d6627ac"><p class="cl-7d65fd40"><span class="cl-7d5ff09e">0.3322</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-7d6627ac"><p class="cl-7d65fd40"><span class="cl-7d5ff09e">504</span></p></td>
<td class="cl-7d6627ac"><p class="cl-7d65fd40"><span class="cl-7d5ff09e">0.8083</span></p></td>
<td class="cl-7d6627ac"><p class="cl-7d65fd40"><span class="cl-7d5ff09e">0.4816</span></p></td>
<td class="cl-7d6627ac"><p class="cl-7d65fd40"><span class="cl-7d5ff09e">0.3309</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-7d6627ac"><p class="cl-7d65fd40"><span class="cl-7d5ff09e">672</span></p></td>
<td class="cl-7d6627ac"><p class="cl-7d65fd40"><span class="cl-7d5ff09e">0.7019</span></p></td>
<td class="cl-7d6627ac"><p class="cl-7d65fd40"><span class="cl-7d5ff09e">0.4497</span></p></td>
<td class="cl-7d6627ac"><p class="cl-7d65fd40"><span class="cl-7d5ff09e">0.3798</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-7d6627ac"><p class="cl-7d65fd40"><span class="cl-7d5ff09e">840</span></p></td>
<td class="cl-7d6627ac"><p class="cl-7d65fd40"><span class="cl-7d5ff09e">0.6038</span></p></td>
<td class="cl-7d6627ac"><p class="cl-7d65fd40"><span class="cl-7d5ff09e">0.4851</span></p></td>
<td class="cl-7d6627ac"><p class="cl-7d65fd40"><span class="cl-7d5ff09e">0.3757</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-7d6627ac"><p class="cl-7d65fd40"><span class="cl-7d5ff09e">1,008</span></p></td>
<td class="cl-7d6627ac"><p class="cl-7d65fd40"><span class="cl-7d5ff09e">0.7386</span></p></td>
<td class="cl-7d6627ac"><p class="cl-7d65fd40"><span class="cl-7d5ff09e">0.5332</span></p></td>
<td class="cl-7d6627ac"><p class="cl-7d65fd40"><span class="cl-7d5ff09e">0.3798</span></p></td>
</tr>
</tbody>
</table></div>
</div>
<div style="margin-left: 25px; margin-right: 20px;">
<p>Plot the data.</p>
</div>
<ol start="3" style="list-style-type: lower-alpha">
<li>The above plot suggests a relationship of the form:</li>
</ol>
<p><span class="math display">\[
y = \alpha - \alpha e^{\gamma x} = \alpha (1 - e^{\gamma x}).
\]</span></p>
<div style="margin-left: 25px; margin-right: 20px;">
<p>Explain the term: <em><span style="color:#FF9966">nonlinear regression</span></em>. Use <code><a href="https://rdrr.io/r/stats/nls.html">nls()</a></code> to estimate the parameters <span class="math inline">\(\alpha\)</span> and <span class="math inline">\(\gamma\)</span> in the above model. What effect does the changing of the start values have on the result of <code><a href="https://rdrr.io/r/stats/nls.html">nls()</a></code>? Experiment with different start values for the parameters. Add the estimated line to the plot in (b) and interpret the graph.</p>
</div>
</div>
</div>
<div id="detailed-example-analysis-of-variance-and-covariance" class="section level2" number="12.14">
<h2>
<span class="header-section-number">12.14</span> Detailed example: Analysis of Variance and Covariance<a class="anchor" aria-label="anchor" href="#detailed-example-analysis-of-variance-and-covariance"><i class="fas fa-link"></i></a>
</h2>
<div id="AnovaOneWay" class="section level3" number="12.14.1">
<h3>
<span class="header-section-number">12.14.1</span> One-way ANOVA models<a class="anchor" aria-label="anchor" href="#AnovaOneWay"><i class="fas fa-link"></i></a>
</h3>
<p>About 90 percent of the ozone in the atmosphere is contained in the stratosphere. Although only a small proportion of atmospheric ozone is found in the troposphere this ozone plays an important role in various climatic phenomena. Research has shown the highest amounts of ozone over the Arctic are found during the spring months of March and April, while the Antarctic has its lowest amounts of ozone during its autumn months of September and October, Atmospheric carbon dioxide not only plays an important role in global warming but its concentration is related to height above sea level and ocean temperature. In order to study relationships between ozone levels, CO_2 concentration, height above sea level, ocean and seasonality a small-scale simulation study has been undertaken. A very simple model was constructed for simulating the data called <code>climate.sim</code>. This simple simulation procedure was performed as described below. Here we show how the <code>climate.sim</code> data were subjected to various, ANOVA, regression and ANCOVA procedures.</p>
<div class="sourceCode" id="cb21"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span> <span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span> <span class="op">(</span><span class="fl">7343</span><span class="op">)</span></span>
<span><span class="va">ocean</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span> <span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span> <span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span> <span class="op">(</span><span class="st">"N-Atlantic"</span>, <span class="fl">20</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span> <span class="op">(</span><span class="st">"S-Atlantic"</span>, <span class="fl">20</span><span class="op">)</span>, </span>
<span>                    <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span> <span class="op">(</span><span class="st">"Indian"</span>, <span class="fl">20</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">season</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span> <span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span> <span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span> <span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span> <span class="op">(</span><span class="st">"summer"</span>, <span class="st">"autumn"</span>, <span class="st">"winter"</span>, <span class="st">"spring"</span><span class="op">)</span>, </span>
<span>                            each <span class="op">=</span> <span class="fl">5</span><span class="op">)</span>, <span class="fl">3</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">height</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Uniform.html">runif</a></span> <span class="op">(</span><span class="fl">60</span>, <span class="fl">100</span>, <span class="fl">750</span><span class="op">)</span></span>
<span><span class="va">climate.sim</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://tibble.tidyverse.org/reference/tibble.html">tibble</a></span> <span class="op">(</span><span class="va">ocean</span>, <span class="va">season</span>, <span class="va">height</span><span class="op">)</span></span>
<span><span class="va">CO2</span> <span class="op">&lt;-</span> <span class="fl">350</span> <span class="op">+</span> <span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span> <span class="op">(</span><span class="va">ocean</span><span class="op">)</span> <span class="op">-</span> <span class="fl">2</span><span class="op">)</span> <span class="op">+</span> <span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span> <span class="op">(</span><span class="va">season</span><span class="op">)</span> <span class="op">-</span> <span class="fl">2.5</span><span class="op">)</span> <span class="op">*</span> <span class="fl">1.8</span> <span class="op">+</span> </span>
<span>       <span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span> <span class="op">(</span><span class="va">ocean</span><span class="op">)</span> <span class="op">-</span> <span class="fl">2</span><span class="op">)</span> <span class="op">*</span> <span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span> <span class="op">(</span><span class="va">season</span><span class="op">)</span> <span class="op">-</span> <span class="fl">2.5</span><span class="op">)</span> <span class="op">*</span> <span class="fl">2</span> <span class="op">-</span></span>
<span>       <span class="fl">0.012</span> <span class="op">*</span> <span class="op">(</span><span class="va">height</span> <span class="op">-</span> <span class="fl">390</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span> <span class="op">(</span><span class="fl">60</span>, <span class="fl">0</span>, <span class="fl">2</span><span class="op">)</span></span>
<span><span class="va">ozone</span> <span class="op">&lt;-</span> <span class="fl">15</span> <span class="op">+</span> <span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span> <span class="op">(</span><span class="va">ocean</span><span class="op">)</span> <span class="op">-</span> <span class="fl">2</span><span class="op">)</span> <span class="op">+</span> <span class="fl">0.02</span> <span class="op">*</span> <span class="op">(</span><span class="va">height</span> <span class="op">-</span> <span class="fl">390</span><span class="op">)</span> <span class="op">+</span> </span>
<span>         <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span> <span class="op">(</span><span class="fl">60</span>, <span class="fl">0</span>, <span class="fl">0.4</span><span class="op">)</span></span>
<span><span class="va">climate.sim</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span> <span class="op">(</span><span class="va">climate.sim</span>, <span class="va">CO2</span>, <span class="va">ozone</span><span class="op">)</span></span></code></pre></div>
<p>The researcher would like to know whether the CO2 levels are the same in the three oceanic regions. Analysis of variance decomposes the total variance in the dependent variable into a between-groups variance and a within-groups variance (or error variance). The underlying model can be written as</p>
<p><span class="math display">\[
Y_{ij} = \mu + \alpha_i + \epsilon_{ij}
\]</span></p>
<p>where <span class="math inline">\(Y_{ij}\)</span> represents the value of the numeric dependent variable for observation <span class="math inline">\(j\)</span> coming from population <span class="math inline">\(i\)</span>; <span class="math inline">\(\mu\)</span> is an effect common to all observations; <span class="math inline">\(\alpha_i\)</span> represents an effect found only in population <span class="math inline">\(i\)</span> and <span class="math inline">\(\epsilon_{ij}\)</span> is an effect (e.g. measurement error) that is specific to only observation (<span class="math inline">\(ij\)</span>). It is assumed that the <span class="math inline">\(\epsilon_{ij}\)</span> is normally distributed with a mean of zero and a constant variance <span class="math inline">\(\sigma^2\)</span> (i.e. the variance is the same in each of the populations). The statistical models to be tested is</p>
<p><span class="math display">\[
H_0: \alpha_1 = \alpha_2 = \dots = \alpha_k
\]</span></p>
<p>where <span class="math inline">\(k\)</span> denotes the number of different populations, versus</p>
<p><span class="math display">\[
H_A: \text{At least one of the } \alpha \text{s differs from the rest}.
\]</span></p>
<p>In general <span class="math inline">\(\mu, \alpha_1, \dots, \alpha_k\)</span> cannot all be estimated uniquely. In order for a statistical hypothesis to be <em><span style="color:#FF9966">testable</span></em> it must be expressed in terms of <em><span style="color:#FF9966">estimable functions</span></em> of the parameters. A statistical hypothesis can often be expressed in different equivalent forms. The null hypothesis above, for example, is equivalent to the following hypotheses:</p>
<p><span class="math display">\[
H_0': \mu+\alpha_1 = \mu+\alpha_2 = \dots = \mu+\alpha_k
\]</span></p>
<p><span class="math display">\[
H_0'': \alpha_1 - \alpha_k = \alpha_2 - \alpha_k = \dots = \alpha_{k-1} - \alpha_k = 0
\]</span></p>
<p>The latter two hypotheses are both in terms of <span class="math inline">\(k - 1\)</span> linearly independent estimable functions and hence are testable. The default behaviour of R is to estimate <span class="math inline">\(\mu\)</span> (the intercept) using the data, take (estimate) one of the <span class="math inline">\(\alpha\)</span>s as zero and then estimate the remainder of the <span class="math inline">\(\alpha\)</span>s as deviations from the estimated intercept using the data. Notice, that in doing so the given null hypothesis above can still be tested.</p>
<ol style="list-style-type: lower-alpha">
<li>Use <code>str(climate.sim)</code> to inspect the structure of the R object <code>climate.sim</code>. Note that the factor season has 4 levels, with the first two levels “autumn” and “spring”. R automatically order the levels alphabetically. In this case, we want the seasons to follow in the order we observe them, especially when making plots, such as <code>boxplot (CO2 ~ season, data = climate.sim)</code>.</li>
</ol>
<div style="margin-left: 25px; margin-right: 20px;">
<p>To change the order of the levels, the R function <code><a href="https://rdrr.io/r/stats/relevel.html">relevel()</a></code> allows putting a specific level first. Sequentially calling this function, allows one to place the levels in any required order. As part of the tidyverse ecosystem, the package <code>forcats</code> is loaded and the following calls allows the user to change the order of the levels in a single call.</p>
</div>
<div class="sourceCode" id="cb22"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">climate.sim</span><span class="op">$</span><span class="va">season</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://forcats.tidyverse.org/reference/fct_relevel.html">fct_relevel</a></span> <span class="op">(</span><span class="va">climate.sim</span><span class="op">$</span><span class="va">season</span>, </span>
<span>                                   <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"summer"</span>, <span class="st">"autumn"</span>, <span class="st">"winter"</span>, <span class="st">"spring"</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/str.html">str</a></span><span class="op">(</span><span class="va">climate.sim</span><span class="op">)</span></span>
<span><span class="co">#&gt; tibble [60 × 5] (S3: tbl_df/tbl/data.frame)</span></span>
<span><span class="co">#&gt;  $ ocean : Factor w/ 3 levels "Indian","N-Atlantic",..: 2 2 2 2 2 2 2 2 2 2 ...</span></span>
<span><span class="co">#&gt;  $ season: Factor w/ 4 levels "summer","autumn",..: 1 1 1 1 1 2 2 2 2 2 ...</span></span>
<span><span class="co">#&gt;  $ height: num [1:60] 534 477 633 256 267 ...</span></span>
<span><span class="co">#&gt;  $ CO2   : num [1:60] 350 348 347 352 355 ...</span></span>
<span><span class="co">#&gt;  $ ozone : num [1:60] 17.5 17.1 20.4 12.1 11.9 ...</span></span></code></pre></div>
<ol start="2" style="list-style-type: lower-alpha">
<li><p>Use <code><a href="https://rdrr.io/r/base/with.html">with()</a></code> and <code><a href="https://rdrr.io/r/base/tapply.html">tapply()</a></code> to obtain the mean and the standard deviation of CO2 for the different seasons.</p></li>
<li><p>Test if the effects of the four seasons on CO2 are the same by executing the R command <code>lm (CO2 ~ season, data = climate.sim)</code> and using the commands <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> and <code><a href="https://rdrr.io/r/stats/anova.html">anova()</a></code>.</p></li>
<li><p>Use <code><a href="https://rdrr.io/r/stats/coef.html">coefficients()</a></code> and interpret the estimates referring to (b).</p></li>
<li><p>Obtain the residuals and plot them against the fitted values. Use different colours for the different seasons. Interpret the plot.</p></li>
</ol>
</div>
<div id="two-way-anova-models-main-effects-and-interaction-effects" class="section level3" number="12.14.2">
<h3>
<span class="header-section-number">12.14.2</span> Two-way ANOVA models: main effects and interaction effects<a class="anchor" aria-label="anchor" href="#two-way-anova-models-main-effects-and-interaction-effects"><i class="fas fa-link"></i></a>
</h3>
<p>Inspection of the <code>climate.sim</code> data by requesting <code>str(climate.sim)</code> reveals the presence of a second factor variable ocean.</p>
<p>We are interested in CO2 as a function of the two factor variables season and ocean. In addition to the <em><span style="color:#FF9966">main effects</span></em> of season and ocean, respectively, we also have to consider <em><span style="color:#FF9966">interaction effects</span></em>.</p>
<p><em><span style="color:#FF9966">Interaction can be defined as the result where the effect of one factor depends on the level of another factor.</span></em></p>
<p>In order to provide for a second factor together with interaction effects the two-way model is given by</p>
<p><span class="math display">\[
Y_{ij} = \mu + \alpha_i + \beta_j + (\alpha\beta)_{ij} + \epsilon_{ij}
\]</span></p>
<p>In this model <span class="math inline">\(\alpha\)</span> represents the main effect of season and <span class="math inline">\(\beta\)</span> the main effect of ocean while the interaction effect is represented by <span class="math inline">\((\alpha\beta)_{ij}\)</span>. The first hypothesis to be tested is the null hypothesis that there exist no interaction effects or that the interaction effects are negligible. Symbolically this is the hypothesis</p>
<p><span class="math display">\[
H_0: (\alpha\beta)_{11} = (\alpha\beta)_{12} = \dots = (\alpha\beta)_{km}
\]</span></p>
<p>where <span class="math inline">\(k\)</span> denotes the number of levels in the first factor variable and <span class="math inline">\(m\)</span> the number of levels in the second factor variable. In order to test for interaction we must have <span class="math inline">\(r &gt; 1\)</span> repetitions (replicates) of each <span class="math inline">\(\alpha_i\beta_j\)</span> combination. The value of <span class="math inline">\(r\)</span> in our example can be found using the following code:</p>
<div class="sourceCode" id="cb23"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/with.html">with</a></span><span class="op">(</span><span class="va">climate.sim</span>, <span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="va">season</span>, <span class="va">ocean</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt;         ocean</span></span>
<span><span class="co">#&gt; season   Indian N-Atlantic S-Atlantic</span></span>
<span><span class="co">#&gt;   summer      5          5          5</span></span>
<span><span class="co">#&gt;   autumn      5          5          5</span></span>
<span><span class="co">#&gt;   winter      5          5          5</span></span>
<span><span class="co">#&gt;   spring      5          5          5</span></span></code></pre></div>
<p>From the table above it is clear that all treatment combinations occur exactly the same number of times. Had there been some missing values in the data, the correct solution to the problem is to estimate the missing values by the mean values of the available data in the affected cells. These values are then substituted in place of the missing values to form a complete data set. The ANOVA is then performed on the complete data set but the degrees of freedom for error is reduced with the number of missing values.</p>
<p>The presence of interaction can be investigated with an interaction plot using the following instruction</p>
<div class="sourceCode" id="cb24"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/with.html">with</a></span><span class="op">(</span><span class="va">climate.sim</span>, <span class="fu"><a href="https://rdrr.io/r/stats/interaction.plot.html">interaction.plot</a></span> <span class="op">(</span><span class="va">ocean</span>, <span class="va">season</span>, response <span class="op">=</span> <span class="va">CO2</span><span class="op">)</span><span class="op">)</span> </span></code></pre></div>
<div class="figure">
<span style="display:block;" id="fig:interactionSeasonOcean"></span>
<img src="11-modelling_files/figure-html/interactionSeasonOcean-1.png" alt="Interaction plot of factors season and ocean associates with the dependent variable CO2" width="100%"><p class="caption">
Figure 12.2: Interaction plot of factors season and ocean associates with the dependent variable CO2
</p>
</div>
<p>What can be deduced from Figure <a href="modelling.html#fig:interactionSeasonOcean">12.2</a>? Explain in detail.</p>
<p>The formal ANOVA can be performed with the instruction</p>
<div class="sourceCode" id="cb25"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">two.way.anova</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">CO2</span> <span class="op">~</span> <span class="va">season</span> <span class="op">+</span> <span class="va">ocean</span> <span class="op">+</span> <span class="va">season</span><span class="op">:</span><span class="va">ocean</span>, data<span class="op">=</span><span class="va">climate.sim</span><span class="op">)</span></span></code></pre></div>
<p>An analysis-of-variance table can be constructed with the instruction:</p>
<div class="sourceCode" id="cb26"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">two.way.anova</span><span class="op">)</span></span>
<span><span class="co">#&gt; Analysis of Variance Table</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Response: CO2</span></span>
<span><span class="co">#&gt;              Df Sum Sq Mean Sq F value   Pr(&gt;F)   </span></span>
<span><span class="co">#&gt; season        3 146.93  48.977  4.9041 0.004718 **</span></span>
<span><span class="co">#&gt; ocean         2  44.20  22.099  2.2128 0.120437   </span></span>
<span><span class="co">#&gt; season:ocean  6 170.41  28.401  2.8439 0.018870 * </span></span>
<span><span class="co">#&gt; Residuals    48 479.37   9.987                    </span></span>
<span><span class="co">#&gt; ---</span></span>
<span><span class="co">#&gt; Signif. codes:  </span></span>
<span><span class="co">#&gt; 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</span></span></code></pre></div>
<p>It is clear from the above table that the null hypothesis of no interaction is to be rejected. This means that it would not make sense to test the main effects of season and ocean. On the other hand, if no significant interaction would have been found then the F-values associated with the two main effects could have been investigated to conclude if none, one or both of the main effects are significant.</p>
<ol style="list-style-type: lower-alpha">
<li><p>Repeat the above analysis using in turn each of the other numeric variables as the response variable.</p></li>
<li><p>Plot the residuals versus the fitted values and interpret the graphs. What can be concluded regarding the assumptions of the two-way ANOVA model?</p></li>
</ol>
<div id="types-of-anova-tables" class="section level4" number="12.14.2.1">
<h4>
<span class="header-section-number">12.14.2.1</span> Types of ANOVA tables<a class="anchor" aria-label="anchor" href="#types-of-anova-tables"><i class="fas fa-link"></i></a>
</h4>
<p>Suppose we want to fit an ANOVA model for the effect of <code>Origin</code> and <code>AirBags</code> on <code>Max.Price</code> in the <code>Cars93</code> data set in package <code>MASS</code>. Notice the difference in the two ANOVA tables below.</p>
<div class="sourceCode" id="cb27"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span> <span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span> <span class="op">(</span><span class="va">Max.Price</span> <span class="op">~</span> <span class="va">AirBags</span> <span class="op">+</span> <span class="va">Origin</span>, data <span class="op">=</span> <span class="va">Cars93</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt; Analysis of Variance Table</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Response: Max.Price</span></span>
<span><span class="co">#&gt;           Df Sum Sq Mean Sq F value    Pr(&gt;F)    </span></span>
<span><span class="co">#&gt; AirBags    2 3462.5 1731.26 20.6885 4.182e-08 ***</span></span>
<span><span class="co">#&gt; Origin     1  283.5  283.51  3.3879   0.06901 .  </span></span>
<span><span class="co">#&gt; Residuals 89 7447.7   83.68                      </span></span>
<span><span class="co">#&gt; ---</span></span>
<span><span class="co">#&gt; Signif. codes:  </span></span>
<span><span class="co">#&gt; 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span> <span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span> <span class="op">(</span><span class="va">Max.Price</span> <span class="op">~</span> <span class="va">Origin</span> <span class="op">+</span> <span class="va">AirBags</span>, data <span class="op">=</span> <span class="va">Cars93</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt; Analysis of Variance Table</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Response: Max.Price</span></span>
<span><span class="co">#&gt;           Df Sum Sq Mean Sq F value    Pr(&gt;F)    </span></span>
<span><span class="co">#&gt; Origin     1  160.5  160.46  1.9175    0.1696    </span></span>
<span><span class="co">#&gt; AirBags    2 3585.6 1792.78 21.4237 2.539e-08 ***</span></span>
<span><span class="co">#&gt; Residuals 89 7447.7   83.68                      </span></span>
<span><span class="co">#&gt; ---</span></span>
<span><span class="co">#&gt; Signif. codes:  </span></span>
<span><span class="co">#&gt; 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</span></span></code></pre></div>
<p>R computes sums of squares for each term, based on the assumption that all terms listed above that particular term in the ANOVA table are already included in the model. The effect is that the order in which terms are specified (specifically for unbalanced data) influences the results.</p>
<p>The R package <code>car</code> provides options to specify how sums of squares are computed:</p>
<ul>
<li><p><strong>Type I</strong>: Sums of squares are computed based on the assumption that all terms specified before the particular term is included in the model.</p></li>
<li><p><strong>Type II</strong>: Sums of squares are computed according to the principle of marginality, testing each term after all others, except ignoring the term’s higher-order interactions.</p></li>
<li><p><strong>Type III</strong>: Sums of squares are computed testing each term in the model after all the others are included in the model. The computation of these sums of squares violate marginality.</p></li>
</ul>
<div class="sourceCode" id="cb28"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span> <span class="op">(</span><span class="va"><a href="https://r-forge.r-project.org/projects/car/">car</a></span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span> <span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span> <span class="op">(</span><span class="va">Max.Price</span> <span class="op">~</span> <span class="va">AirBags</span> <span class="op">*</span> <span class="va">Origin</span>, data <span class="op">=</span> <span class="va">Cars93</span><span class="op">)</span><span class="op">)</span>   <span class="co"># type = "I"</span></span>
<span><span class="co">#&gt; Analysis of Variance Table</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Response: Max.Price</span></span>
<span><span class="co">#&gt;                Df Sum Sq Mean Sq F value    Pr(&gt;F)    </span></span>
<span><span class="co">#&gt; AirBags         2 3462.5 1731.26 21.4712 2.636e-08 ***</span></span>
<span><span class="co">#&gt; Origin          1  283.5  283.51  3.5161   0.06413 .  </span></span>
<span><span class="co">#&gt; AirBags:Origin  2  432.8  216.38  2.6835   0.07398 .  </span></span>
<span><span class="co">#&gt; Residuals      87 7015.0   80.63                      </span></span>
<span><span class="co">#&gt; ---</span></span>
<span><span class="co">#&gt; Signif. codes:  </span></span>
<span><span class="co">#&gt; 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/car/man/Anova.html">Anova</a></span> <span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span> <span class="op">(</span><span class="va">Max.Price</span> <span class="op">~</span> <span class="va">AirBags</span> <span class="op">*</span> <span class="va">Origin</span>, data <span class="op">=</span> <span class="va">Cars93</span><span class="op">)</span>, type <span class="op">=</span> <span class="st">"II"</span><span class="op">)</span></span>
<span><span class="co">#&gt; Anova Table (Type II tests)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Response: Max.Price</span></span>
<span><span class="co">#&gt;                Sum Sq Df F value    Pr(&gt;F)    </span></span>
<span><span class="co">#&gt; AirBags        3585.6  2 22.2342 1.586e-08 ***</span></span>
<span><span class="co">#&gt; Origin          283.5  1  3.5161   0.06413 .  </span></span>
<span><span class="co">#&gt; AirBags:Origin  432.8  2  2.6835   0.07398 .  </span></span>
<span><span class="co">#&gt; Residuals      7015.0 87                      </span></span>
<span><span class="co">#&gt; ---</span></span>
<span><span class="co">#&gt; Signif. codes:  </span></span>
<span><span class="co">#&gt; 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/car/man/Anova.html">Anova</a></span> <span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span> <span class="op">(</span><span class="va">Max.Price</span> <span class="op">~</span> <span class="va">AirBags</span> <span class="op">*</span> <span class="va">Origin</span>, data <span class="op">=</span> <span class="va">Cars93</span><span class="op">)</span>, type <span class="op">=</span> <span class="st">"III"</span><span class="op">)</span></span>
<span><span class="co">#&gt; Anova Table (Type III tests)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Response: Max.Price</span></span>
<span><span class="co">#&gt;                Sum Sq Df F value    Pr(&gt;F)    </span></span>
<span><span class="co">#&gt; (Intercept)    6405.3  1 79.4394 6.773e-14 ***</span></span>
<span><span class="co">#&gt; AirBags         855.9  2  5.3078  0.006684 ** </span></span>
<span><span class="co">#&gt; Origin          574.5  1  7.1253  0.009067 ** </span></span>
<span><span class="co">#&gt; AirBags:Origin  432.8  2  2.6835  0.073977 .  </span></span>
<span><span class="co">#&gt; Residuals      7015.0 87                      </span></span>
<span><span class="co">#&gt; ---</span></span>
<span><span class="co">#&gt; Signif. codes:  </span></span>
<span><span class="co">#&gt; 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</span></span></code></pre></div>
<p>If we focus on the type II tests, we notice that the sums of squares for interaction (432.8) corresponds to the sums of squares for the last term in the type I table. The sums of squares for <code>Origin</code> (283.5) corresponds to the sums of squares value when specifying <code>Max.Price ~ AirBags + Origin</code> and the sums of squares for <code>AirBags</code> (3585.6) corresponds to the sums of squares when specifying <code>Max.Price ~ Origin + AirBags</code>.</p>
<p>In the ANOVA table with type III tests, the interaction sums of squares agrees with the other two tables, but because the marginality principle is violated, the sums of squares for the main effects are different. Care should be taken when testing hypotheses with type III sums of squares.</p>
</div>
</div>
<div id="one-way-ancova-models" class="section level3" number="12.14.3">
<h3>
<span class="header-section-number">12.14.3</span> One-way ANCOVA models<a class="anchor" aria-label="anchor" href="#one-way-ancova-models"><i class="fas fa-link"></i></a>
</h3>
<p>A scatterplot of CO2 versus height suggests the possibility of a linear relationship between these two numeric variables. Check the above statement.</p>
<p>This means that the ANOVA model is not the correct model to use for the <code>climate.sim</code> data. Instead we should consider a one-way ANCOVA model with height as a <em><span style="color:#FF9966">concomitant variable</span></em>:</p>
<p><span class="math display">\[
Y_{ij} = \mu + \alpha_i + \beta_i x_{ij} + \epsilon_{ij}
\]</span></p>
<p>where <span class="math inline">\(i = 1, 2, \dots, k\)</span>; <span class="math inline">\(j = 1, 2, \dots, n_i\)</span>.</p>
<p>In this model <span class="math inline">\(x_{ij}\)</span> represents a continuous (or numeric) variable that is measured together with the dependent continuous variable <span class="math inline">\(Y_{ij}\)</span>. If variable <span class="math inline">\(x\)</span> has a significant relationship with the dependent (response) variable the values of the latter should be adjusted before performing a one-way ANOVA. The researcher must first ascertain whether the regression coefficients (i.e. the slopes of the regression lines) of the different groups are the same. Therefore, <span style="color:#FF9966">Step I</span> of a covariance analysis investigates</p>
<p><span class="math display">\[
H_{01}: \beta_1 = \beta_2 = \dots = \beta_k
\]</span></p>
<p>and if this is not the case, then the analysis proceeds by (i) estimating the regression parameters <span class="math inline">\(\beta_1, \beta_2, \dots, \beta_k\)</span> for every group/treatment/level individually and (ii) by investigating the differences between the <span class="math inline">\(y\)</span>-means of the <span class="math inline">\(k\)</span> groups at specific values of <span class="math inline">\(x\)</span>. On the other hand, if Step I shows that it can be assumed that <span class="math inline">\(\beta_1 = \beta_2 = \dots = \beta_k = (\beta)\)</span> then the <span class="math inline">\(\beta_i\)</span> in the model is replaced by the common <span class="math inline">\(\beta\)</span> and <span style="color:#FF9966">Step II</span> is carried out. Step II then consists of determining whether there is a significant regression relationship, i.e. the null hypothesis</p>
<p><span class="math display">\[
H_{02}: \beta = 0
\]</span></p>
<p>is tested. If it can be assumed that <span class="math inline">\(\beta = 0\)</span>, then an ordinary analysis of variance can be carried out. If <span class="math inline">\(\beta \neq 0\)</span>, <span style="color:#FF9966">Step III</span> of ANCOVA is executed which first consists of adjusting the <span class="math inline">\(y_{ij}\)</span>-observations for their regression relationship with the <span class="math inline">\(\{x_{ij} \}\)</span>. An analysis of variance is then carried out on the adjusted <span class="math inline">\(\{y_{ij} \}\)</span> in order to ascertain whether the levels of the experimental factor have similar effects or not.</p>
<p>As an example we will again make use of the data of the <code>climate.sim</code> data set constructed above.</p>
<ol style="list-style-type: lower-alpha">
<li><p>Obtain a scatterplot of CO2 as a function of height. Use different colours for the three oceans. What can be deduced from the scatterplot?</p></li>
<li><p>Carry out a one-way ANOVA of CO2 measured in the three different ocean locations.</p></li>
<li><p>Perform Step I of a one-way ANCOVA using the commands:</p></li>
</ol>
<div class="sourceCode" id="cb29"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">one.way.ancova.I</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span> <span class="op">(</span><span class="va">CO2</span> <span class="op">~</span> <span class="va">ocean</span> <span class="op">+</span> <span class="va">height</span> <span class="op">+</span> <span class="va">ocean</span><span class="op">:</span><span class="va">height</span>, data <span class="op">=</span> <span class="va">climate.sim</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/car/man/Anova.html">Anova</a></span><span class="op">(</span><span class="va">one.way.ancova.I</span>, type <span class="op">=</span> <span class="st">"II"</span><span class="op">)</span></span>
<span><span class="co">#&gt; Anova Table (Type II tests)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Response: CO2</span></span>
<span><span class="co">#&gt;              Sum Sq Df F value    Pr(&gt;F)    </span></span>
<span><span class="co">#&gt; ocean         42.94  2  1.8288 0.1704134    </span></span>
<span><span class="co">#&gt; height       156.47  1 13.3290 0.0005907 ***</span></span>
<span><span class="co">#&gt; ocean:height   6.31  2  0.2689 0.7652300    </span></span>
<span><span class="co">#&gt; Residuals    633.93 54                      </span></span>
<span><span class="co">#&gt; ---</span></span>
<span><span class="co">#&gt; Signif. codes:  </span></span>
<span><span class="co">#&gt; 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coefficients</a></span><span class="op">(</span><span class="va">one.way.ancova.I</span><span class="op">)</span></span>
<span><span class="co">#&gt;            (Intercept)        oceanN-Atlantic </span></span>
<span><span class="co">#&gt;          352.451112469            0.822464321 </span></span>
<span><span class="co">#&gt;        oceanS-Atlantic                 height </span></span>
<span><span class="co">#&gt;            0.155359967           -0.010909055 </span></span>
<span><span class="co">#&gt; oceanN-Atlantic:height oceanS-Atlantic:height </span></span>
<span><span class="co">#&gt;            0.002428426            0.004214614</span></span></code></pre></div>
<div style="margin-left: 25px; margin-right: 20px;">
<p><em>Interpretation of the ANOVA table</em></p>
<p>First look at interaction effect in the anova table. It provides information on whether the hypothesis <span class="math inline">\(\beta_1 = \beta_2 = \beta_3\)</span> should be rejected. Since the conclusion is that all three β’s are the same (differences are negligent) then (and only then) inspect the line for the concomitant variable height to decide if the common slope <span class="math inline">\(\beta = 0\)</span>. This is Step II. If it can be concluded that the common slope is zero then the ANOVA of section <a href="modelling.html#AnovaOneWay">12.14.1</a> is performed.</p>
<p>In Step II it is concluded that the common slope is not equal to zero so we perform Step III by calling, for example,</p>
</div>
<div class="sourceCode" id="cb30"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">one.way.ancova.III</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span> <span class="op">(</span><span class="va">CO2</span> <span class="op">~</span> <span class="va">ocean</span> <span class="op">+</span> <span class="va">height</span>, data <span class="op">=</span> <span class="va">climate.sim</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/car/man/Anova.html">Anova</a></span> <span class="op">(</span><span class="va">one.way.ancova.III</span>, type <span class="op">=</span> <span class="st">"II"</span><span class="op">)</span></span>
<span><span class="co">#&gt; Anova Table (Type II tests)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Response: CO2</span></span>
<span><span class="co">#&gt;           Sum Sq Df F value    Pr(&gt;F)    </span></span>
<span><span class="co">#&gt; ocean      42.94  2  1.8778 0.1624241    </span></span>
<span><span class="co">#&gt; height    156.47  1 13.6864 0.0004941 ***</span></span>
<span><span class="co">#&gt; Residuals 640.24 56                      </span></span>
<span><span class="co">#&gt; ---</span></span>
<span><span class="co">#&gt; Signif. codes:  </span></span>
<span><span class="co">#&gt; 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</span></span></code></pre></div>
<div style="margin-left: 25px; margin-right: 20px;">
<p><em>Note that if you are not using type II sums of squares, but the default <code><a href="https://rdrr.io/r/stats/anova.html">anova()</a></code> function in the latter call the numeric concomitant variable MUST PRECEDE the categorical variable on the right-hand side of the tilde because Step III is only carried out on condition that Step II has indicated a significant relationship between the concomitant variable and the response variable.</em> The line corresponding to the factor variable ocean in the analysis of variance table is then inspected to conclude whether the effects associated with the respective levels of the factor variable are significantly different.</p>
<ol style="list-style-type: lower-roman">
<li>In the example above we conclude that the three β’s in the ANCOVA model are the same and that the hypothesis <span class="math inline">\(\beta = 0\)</span> is rejected. In Step III we conclude that <span class="math inline">\(\alpha_1 = \alpha_2 = \alpha_3\)</span>. Obtain the estimated regression equation using the following instructions:</li>
</ol>
</div>
<div class="sourceCode" id="cb31"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">one.way.ancova.final</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span> <span class="op">(</span><span class="va">CO2</span> <span class="op">~</span> <span class="va">height</span>, data <span class="op">=</span> <span class="va">climate.sim</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coefficients</a></span> <span class="op">(</span><span class="va">one.way.ancova.final</span><span class="op">)</span></span>
<span><span class="co">#&gt;   (Intercept)        height </span></span>
<span><span class="co">#&gt; 352.723551558  -0.008562195</span></span></code></pre></div>
<div style="margin-left: 25px; margin-right: 20px;">
<ol start="2" style="list-style-type: lower-roman">
<li>Add the regression line to the scatterplot constructed in (a). See Figure <a href="modelling.html#fig:CO2oceanHeight">12.3</a>.</li>
</ol>
</div>
<div class="figure">
<span style="display:block;" id="fig:CO2oceanHeight"></span>
<img src="11-modelling_files/figure-html/CO2oceanHeight-1.png" alt="Scatterplot of CO2 vs height with a single regression line." width="100%"><p class="caption">
Figure 12.3: Scatterplot of CO2 vs height with a single regression line.
</p>
</div>
<div style="margin-left: 25px; margin-right: 20px;">
<ol start="3" style="list-style-type: lower-roman">
<li>Inspection of Figure <a href="modelling.html#fig:CO2oceanHeight">12.3</a> shows a negative relationship between CO2 and height but there is no real difference between the observations from the three different oceanic locations.</li>
</ol>
</div>
<ol start="4" style="list-style-type: lower-alpha">
<li>Perform Step I of a one-way ANCOVA of CO2 for the different seasons with height as concomitant variable.</li>
</ol>
<div class="sourceCode" id="cb32"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">one.way.ancova.I</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span> <span class="op">(</span><span class="va">CO2</span> <span class="op">~</span> <span class="va">season</span> <span class="op">+</span> <span class="va">height</span> <span class="op">+</span> <span class="va">season</span><span class="op">:</span><span class="va">height</span>, </span>
<span>                        data <span class="op">=</span> <span class="va">climate.sim</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/car/man/Anova.html">Anova</a></span><span class="op">(</span><span class="va">one.way.ancova.I</span>, type <span class="op">=</span> <span class="st">"II"</span><span class="op">)</span></span>
<span><span class="co">#&gt; Anova Table (Type II tests)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Response: CO2</span></span>
<span><span class="co">#&gt;               Sum Sq Df F value    Pr(&gt;F)    </span></span>
<span><span class="co">#&gt; season        184.54  3  7.4808 0.0002966 ***</span></span>
<span><span class="co">#&gt; height        195.34  1 23.7559 1.069e-05 ***</span></span>
<span><span class="co">#&gt; season:height  71.04  3  2.8799 0.0446297 *  </span></span>
<span><span class="co">#&gt; Residuals     427.59 52                      </span></span>
<span><span class="co">#&gt; ---</span></span>
<span><span class="co">#&gt; Signif. codes:  </span></span>
<span><span class="co">#&gt; 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coefficients</a></span> <span class="op">(</span><span class="va">one.way.ancova.I</span><span class="op">)</span></span>
<span><span class="co">#&gt;         (Intercept)        seasonautumn        seasonwinter </span></span>
<span><span class="co">#&gt;       357.383726918        -9.397968637        -3.706636570 </span></span>
<span><span class="co">#&gt;        seasonspring              height seasonautumn:height </span></span>
<span><span class="co">#&gt;        -3.832972292        -0.018192410         0.015544922 </span></span>
<span><span class="co">#&gt; seasonwinter:height seasonspring:height </span></span>
<span><span class="co">#&gt;         0.012766975         0.006214125</span></span></code></pre></div>
<div style="margin-left: 25px; margin-right: 20px;">
<p><em>Interpretation of the ANOVA table</em></p>
<p>First look at the line for interaction. This line provides information on whether the hypothesis <span class="math inline">\(\beta_1 = \beta_2 = \beta_3 = \beta_3\)</span> should be rejected (as is the case here. Why?) Therefore we cannot proceed to Step II.</p>
<ol style="list-style-type: lower-roman">
<li>In the example above we conclude that the three β’s in the ANCOVA model are not the same. Obtain the estimated regression equations for each of the seasons using the following instructions:</li>
</ol>
</div>
<div class="sourceCode" id="cb33"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">one.way.ancova.sep.reglns</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span> <span class="op">(</span><span class="va">CO2</span> <span class="op">~</span> <span class="op">-</span><span class="fl">1</span> <span class="op">+</span> <span class="va">season</span><span class="op">/</span><span class="va">height</span>, data <span class="op">=</span> <span class="va">climate.sim</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coefficients</a></span> <span class="op">(</span><span class="va">one.way.ancova.sep.reglns</span><span class="op">)</span></span>
<span><span class="co">#&gt;        seasonsummer        seasonautumn        seasonwinter </span></span>
<span><span class="co">#&gt;       357.383726918       347.985758281       353.677090348 </span></span>
<span><span class="co">#&gt;        seasonspring seasonsummer:height seasonautumn:height </span></span>
<span><span class="co">#&gt;       353.550754626        -0.018192410        -0.002647488 </span></span>
<span><span class="co">#&gt; seasonwinter:height seasonspring:height </span></span>
<span><span class="co">#&gt;        -0.005425435        -0.011978285</span></span></code></pre></div>
<div style="margin-left: 25px; margin-right: 20px;">
<ol start="2" style="list-style-type: lower-roman">
<li>Add the regression lines to the scatterplot of CO2 vs height. See Figure <a href="modelling.html#fig:CO2seasonHeight">12.4</a>.</li>
</ol>
</div>
<pre><code>#&gt; `geom_smooth()` using formula = 'y ~ x'</code></pre>
<div class="figure">
<span style="display:block;" id="fig:CO2seasonHeight"></span>
<img src="11-modelling_files/figure-html/CO2seasonHeight-1.png" alt="Scatterplot of CO2 vs height with a separate regression line for each of the seasons." width="100%"><p class="caption">
Figure 12.4: Scatterplot of CO2 vs height with a separate regression line for each of the seasons.
</p>
</div>
<div style="margin-left: 25px; margin-right: 20px;">
<ol start="3" style="list-style-type: lower-roman">
<li>Inspection of Figure <a href="modelling.html#fig:CO2seasonHeight">12.4</a> shows that the height has a much smaller effect in autumn and winter than in spring and summer.</li>
</ol>
<p>It is clear from Figure @ref(fig:CO2_season_height) that the outcome of a test of the hypothesis that <span class="math inline">\(\alpha_1 = \alpha_2 = \alpha_3 = \alpha_4\)</span> depends on the value of height where the test is performed. At height = 600 the test that <span class="math inline">\(\alpha_1 = \alpha_2 = \alpha_3 = \alpha_4\)</span> is performed as follows:</p>
<p>First notice that the Residual sum of squares in the ANOVA table above is <span class="math inline">\(RSSE=427.59\)</span> with <span class="math inline">\(52\)</span> degrees of freedom. At height = 600 execute:</p>
</div>
<div class="sourceCode" id="cb35"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/car/man/Anova.html">Anova</a></span> <span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span> <span class="op">(</span><span class="va">CO2</span> <span class="op">~</span> <span class="va">season</span><span class="op">:</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/AsIs.html">I</a></span><span class="op">(</span><span class="va">height</span><span class="op">-</span><span class="fl">600</span><span class="op">)</span><span class="op">)</span> , data <span class="op">=</span> <span class="va">climate.sim</span><span class="op">)</span>, type <span class="op">=</span> <span class="st">"II"</span><span class="op">)</span></span>
<span><span class="co">#&gt; Anova Table (Type II tests)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Response: CO2</span></span>
<span><span class="co">#&gt;                        Sum Sq Df F value    Pr(&gt;F)    </span></span>
<span><span class="co">#&gt; season:I(height - 600) 318.53  4  8.3841 2.353e-05 ***</span></span>
<span><span class="co">#&gt; Residuals              522.39 55                      </span></span>
<span><span class="co">#&gt; ---</span></span>
<span><span class="co">#&gt; Signif. codes:  </span></span>
<span><span class="co">#&gt; 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</span></span></code></pre></div>
<div style="margin-left: 25px; margin-right: 20px;">
<p>Now calculate</p>
<p><span class="math display">\[
F_0 = \frac{\frac{522.39 - 427.59}{55-52}}{\frac{427.59}{52}} = 3.8429
\]</span></p>
<p>and the corresponding p-value using the instruction</p>
</div>
<div class="sourceCode" id="cb36"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fl">1</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Fdist.html">pf</a></span> <span class="op">(</span><span class="fl">3.8429</span>, <span class="fl">3</span>, <span class="fl">52</span><span class="op">)</span></span>
<span><span class="co">#&gt; [1] 0.01468944</span></span></code></pre></div>
<div style="margin-left: 25px; margin-right: 20px;">
<p>At height = 400</p>
</div>
<div class="sourceCode" id="cb37"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/car/man/Anova.html">Anova</a></span> <span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span> <span class="op">(</span><span class="va">CO2</span> <span class="op">~</span> <span class="va">season</span><span class="op">:</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/AsIs.html">I</a></span><span class="op">(</span><span class="va">height</span><span class="op">-</span><span class="fl">400</span><span class="op">)</span><span class="op">)</span> , data <span class="op">=</span> <span class="va">climate.sim</span><span class="op">)</span>, type <span class="op">=</span> <span class="st">"II"</span><span class="op">)</span></span>
<span><span class="co">#&gt; Anova Table (Type II tests)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Response: CO2</span></span>
<span><span class="co">#&gt;                        Sum Sq Df F value    Pr(&gt;F)    </span></span>
<span><span class="co">#&gt; season:I(height - 400) 245.34  4  5.6641 0.0006846 ***</span></span>
<span><span class="co">#&gt; Residuals              595.57 55                      </span></span>
<span><span class="co">#&gt; ---</span></span>
<span><span class="co">#&gt; Signif. codes:  </span></span>
<span><span class="co">#&gt; 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</span></span></code></pre></div>
<div style="margin-left: 25px; margin-right: 20px;">
<p>Now</p>
<p><span class="math display">\[
F_0 = \frac{\frac{595.57 - 427.59}{55-52}}{\frac{427.59}{52}} = 6.80945
\]</span></p>
<p>and</p>
</div>
<div class="sourceCode" id="cb38"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fl">1</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Fdist.html">pf</a></span> <span class="op">(</span><span class="fl">6.80945</span>, <span class="fl">3</span>, <span class="fl">52</span><span class="op">)</span></span>
<span><span class="co">#&gt; [1] 0.0005874415</span></span></code></pre></div>
<div style="margin-left: 25px; margin-right: 20px;">
<p>What conclusions can be drawn from the tests at heights of 600 and 400 respectively when using a 1% significance level? Conjecture on the conclusions following a multiple testing procedure after a significant anova result.</p>
</div>
<ol start="5" style="list-style-type: lower-alpha">
<li>Perform Step I of a one-way ANCOVA of ozone for the three oceanic locations with height as concomitant variable.</li>
</ol>
<div class="sourceCode" id="cb39"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">one.way.ancova.I</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span> <span class="op">(</span><span class="va">ozone</span> <span class="op">~</span> <span class="va">ocean</span> <span class="op">+</span> <span class="va">height</span> <span class="op">+</span> <span class="va">ocean</span><span class="op">:</span><span class="va">height</span>, data <span class="op">=</span> <span class="va">climate.sim</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/car/man/Anova.html">Anova</a></span><span class="op">(</span><span class="va">one.way.ancova.I</span>, type <span class="op">=</span> <span class="st">"II"</span><span class="op">)</span></span>
<span><span class="co">#&gt; Anova Table (Type II tests)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Response: ozone</span></span>
<span><span class="co">#&gt;              Sum Sq Df   F value Pr(&gt;F)    </span></span>
<span><span class="co">#&gt; ocean         40.28  2  127.6912 &lt;2e-16 ***</span></span>
<span><span class="co">#&gt; height       878.66  1 5571.0063 &lt;2e-16 ***</span></span>
<span><span class="co">#&gt; ocean:height   0.52  2    1.6603 0.1996    </span></span>
<span><span class="co">#&gt; Residuals      8.52 54                     </span></span>
<span><span class="co">#&gt; ---</span></span>
<span><span class="co">#&gt; Signif. codes:  </span></span>
<span><span class="co">#&gt; 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coefficients</a></span><span class="op">(</span><span class="va">one.way.ancova.I</span><span class="op">)</span></span>
<span><span class="co">#&gt;            (Intercept)        oceanN-Atlantic </span></span>
<span><span class="co">#&gt;           5.999989e+00           9.596618e-01 </span></span>
<span><span class="co">#&gt;        oceanS-Atlantic                 height </span></span>
<span><span class="co">#&gt;           2.387163e+00           2.054280e-02 </span></span>
<span><span class="co">#&gt; oceanN-Atlantic:height oceanS-Atlantic:height </span></span>
<span><span class="co">#&gt;           8.989381e-05          -9.691870e-04</span></span></code></pre></div>
<div style="margin-left: 25px; margin-right: 20px;">
<p><em>Interpretation of the ANOVA table</em></p>
<p>First look at the line for interaction. We conclude that all three β’s are the same (differences are negligible) and then (and only then) inspect the line for continuous variable height to decide if the common slope β=0. This is Step II. Since it is concluded that the common slope is not zero we proceed to Step III.</p>
</div>
<div class="sourceCode" id="cb40"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">one.way.ancova.III</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span> <span class="op">(</span><span class="va">ozone</span> <span class="op">~</span> <span class="va">ocean</span> <span class="op">+</span> <span class="va">height</span>, data <span class="op">=</span> <span class="va">climate.sim</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/car/man/Anova.html">Anova</a></span><span class="op">(</span><span class="va">one.way.ancova.III</span>, type <span class="op">=</span> <span class="st">"II"</span><span class="op">)</span></span>
<span><span class="co">#&gt; Anova Table (Type II tests)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Response: ozone</span></span>
<span><span class="co">#&gt;           Sum Sq Df F value    Pr(&gt;F)    </span></span>
<span><span class="co">#&gt; ocean      40.28  2  124.75 &lt; 2.2e-16 ***</span></span>
<span><span class="co">#&gt; height    878.66  1 5442.66 &lt; 2.2e-16 ***</span></span>
<span><span class="co">#&gt; Residuals   9.04 56                      </span></span>
<span><span class="co">#&gt; ---</span></span>
<span><span class="co">#&gt; Signif. codes:  </span></span>
<span><span class="co">#&gt; 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coefficients</a></span><span class="op">(</span><span class="va">one.way.ancova.I</span><span class="op">)</span></span>
<span><span class="co">#&gt;            (Intercept)        oceanN-Atlantic </span></span>
<span><span class="co">#&gt;           5.999989e+00           9.596618e-01 </span></span>
<span><span class="co">#&gt;        oceanS-Atlantic                 height </span></span>
<span><span class="co">#&gt;           2.387163e+00           2.054280e-02 </span></span>
<span><span class="co">#&gt; oceanN-Atlantic:height oceanS-Atlantic:height </span></span>
<span><span class="co">#&gt;           8.989381e-05          -9.691870e-04</span></span></code></pre></div>
<div style="margin-left: 25px; margin-right: 20px;">
<p>The line corresponding to the factor variable ocean in the analysis of variance table is inspected to conclude if the effects associated with the respective levels of the factor variable are significantly different.</p>
<ol style="list-style-type: lower-roman">
<li>In the example above we conclude that the three β’s in the ANCOVA model are the same and that the hypothesis β=0 is rejected. In Step III we conclude that the hypothesis <span class="math inline">\(\alpha_1 = \alpha_2 = \alpha_3\)</span> is also rejected. Obtain the estimated regression equations using the following instructions:</li>
</ol>
</div>
<div class="sourceCode" id="cb41"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">one.way.ancova.reglns</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span> <span class="op">(</span><span class="va">ozone</span> <span class="op">~</span> <span class="va">ocean</span> <span class="op">+</span> <span class="va">height</span>, data <span class="op">=</span> <span class="va">climate.sim</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coefficients</a></span><span class="op">(</span><span class="va">one.way.ancova.reglns</span><span class="op">)</span></span>
<span><span class="co">#&gt;     (Intercept) oceanN-Atlantic oceanS-Atlantic </span></span>
<span><span class="co">#&gt;      6.13127497      0.99327355      2.00694355 </span></span>
<span><span class="co">#&gt;          height </span></span>
<span><span class="co">#&gt;      0.02020925</span></span></code></pre></div>
<div style="margin-left: 25px; margin-right: 20px;">
<ol start="2" style="list-style-type: lower-roman">
<li><p>Obtain a scatterplot of ozone as a function of height. Use different colours for the three oceans. Add a separate regression line for each of the oceans (see Figure <a href="modelling.html#fig:ozoneOceanHeight">12.5</a>).</p></li>
<li><p>Inspection of Figure <a href="modelling.html#fig:ozoneOceanHeight">12.5</a> shows three parallel regression lines, since <span class="math inline">\(\beta_1 = \beta_2 = \beta_3\)</span>, with different intercepts. The hypothesis that <span class="math inline">\(\alpha_1 = \alpha_2 = \alpha_3\)</span> is rejected irrespective of the height above sea level.</p></li>
</ol>
</div>
<div class="figure">
<span style="display:block;" id="fig:ozoneOceanHeight"></span>
<img src="11-modelling_files/figure-html/ozoneOceanHeight-1.png" alt="Scatterplot of ozone vs height with a separate parallel regression lines for each of the different oceanic locations." width="100%"><p class="caption">
Figure 12.5: Scatterplot of ozone vs height with a separate parallel regression lines for each of the different oceanic locations.
</p>
</div>
<p>The steps of a one-way analysis of covariance is illustrated in the diagram in Figure <a href="modelling.html#fig:ANCOVA">12.6</a>.</p>
<div class="figure">
<span style="display:block;" id="fig:ANCOVA"></span>
<img src="pics/ANCOVA.jpg" alt="Diagrammatic process flow for a one-way analysis of covariance." width="100%"><p class="caption">
Figure 12.6: Diagrammatic process flow for a one-way analysis of covariance.
</p>
</div>
</div>
<div id="maize-exercise" class="section level3" number="12.14.4">
<h3>
<span class="header-section-number">12.14.4</span> Maize Exercise<a class="anchor" aria-label="anchor" href="#maize-exercise"><i class="fas fa-link"></i></a>
</h3>
<div style="color: #80CC99;">
<p>A researcher investigates if three maize varieties give the same yield. The following data are obtained according to the requirements of a linear model:</p>
<div class="tabwid">
<style>.cl-8174ec48{}.cl-8167eba6{font-family:'Arial';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(102, 102, 102, 1.00);background-color:transparent;}.cl-816cb122{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:3pt;padding-top:3pt;padding-left:3pt;padding-right:3pt;line-height: 1;background-color:transparent;}.cl-816cb136{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:3pt;padding-top:3pt;padding-left:3pt;padding-right:3pt;line-height: 1;background-color:transparent;}.cl-816cda44{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-816cda4e{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-816cda4f{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style>
<div class="inline-table"><table data-quarto-disable-processing="true" class="cl-8174ec48">
<thead>
<tr style="overflow-wrap:break-word;"><th colspan="6" class="cl-816cda44"><p class="cl-816cb122"><span class="cl-8167eba6">VARIETY</span></p></th></tr>
<tr style="overflow-wrap:break-word;">
<th colspan="2" class="cl-816cda44"><p class="cl-816cb122"><span class="cl-8167eba6">KB1</span></p></th>
<th colspan="2" class="cl-816cda44"><p class="cl-816cb122"><span class="cl-8167eba6">KB2</span></p></th>
<th colspan="2" class="cl-816cda44"><p class="cl-816cb122"><span class="cl-8167eba6">KB3</span></p></th>
</tr>
<tr style="overflow-wrap:break-word;">
<th class="cl-816cda4e"><p class="cl-816cb122"><span class="cl-8167eba6">Yield per hectare</span></p></th>
<th class="cl-816cda4e"><p class="cl-816cb122"><span class="cl-8167eba6">Rainfall</span></p></th>
<th class="cl-816cda4e"><p class="cl-816cb122"><span class="cl-8167eba6">Yield per hectare</span></p></th>
<th class="cl-816cda4e"><p class="cl-816cb122"><span class="cl-8167eba6">Rainfall</span></p></th>
<th class="cl-816cda4e"><p class="cl-816cb122"><span class="cl-8167eba6">Yield per hectare</span></p></th>
<th class="cl-816cda4e"><p class="cl-816cb122"><span class="cl-8167eba6">Rainfall</span></p></th>
</tr>
</thead>
<tbody>
<tr style="overflow-wrap:break-word;">
<td class="cl-816cda4f"><p class="cl-816cb136"><span class="cl-8167eba6">17.50</span></p></td>
<td class="cl-816cda4f"><p class="cl-816cb136"><span class="cl-8167eba6">95.90</span></p></td>
<td class="cl-816cda4f"><p class="cl-816cb136"><span class="cl-8167eba6">37.50</span></p></td>
<td class="cl-816cda4f"><p class="cl-816cb136"><span class="cl-8167eba6">114.10</span></p></td>
<td class="cl-816cda4f"><p class="cl-816cb136"><span class="cl-8167eba6">18.75</span></p></td>
<td class="cl-816cda4f"><p class="cl-816cb136"><span class="cl-8167eba6">98.00</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-816cda4f"><p class="cl-816cb136"><span class="cl-8167eba6">45.00</span></p></td>
<td class="cl-816cda4f"><p class="cl-816cb136"><span class="cl-8167eba6">116.20</span></p></td>
<td class="cl-816cda4f"><p class="cl-816cb136"><span class="cl-8167eba6">42.15</span></p></td>
<td class="cl-816cda4f"><p class="cl-816cb136"><span class="cl-8167eba6">119.28</span></p></td>
<td class="cl-816cda4f"><p class="cl-816cb136"><span class="cl-8167eba6">13.75</span></p></td>
<td class="cl-816cda4f"><p class="cl-816cb136"><span class="cl-8167eba6">117.60</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-816cda4f"><p class="cl-816cb136"><span class="cl-8167eba6">38.75</span></p></td>
<td class="cl-816cda4f"><p class="cl-816cb136"><span class="cl-8167eba6">116.20</span></p></td>
<td class="cl-816cda4f"><p class="cl-816cb136"><span class="cl-8167eba6">48.75</span></p></td>
<td class="cl-816cda4f"><p class="cl-816cb136"><span class="cl-8167eba6">121.94</span></p></td>
<td class="cl-816cda4f"><p class="cl-816cb136"><span class="cl-8167eba6">52.50</span></p></td>
<td class="cl-816cda4f"><p class="cl-816cb136"><span class="cl-8167eba6">105.28</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-816cda4f"><p class="cl-816cb136"><span class="cl-8167eba6">33.75</span></p></td>
<td class="cl-816cda4f"><p class="cl-816cb136"><span class="cl-8167eba6">93.10</span></p></td>
<td class="cl-816cda4f"><p class="cl-816cb136"><span class="cl-8167eba6">32.50</span></p></td>
<td class="cl-816cda4f"><p class="cl-816cb136"><span class="cl-8167eba6">97.02</span></p></td>
<td class="cl-816cda4f"><p class="cl-816cb136"><span class="cl-8167eba6">17.50</span></p></td>
<td class="cl-816cda4f"><p class="cl-816cb136"><span class="cl-8167eba6">94.50</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-816cda4f"><p class="cl-816cb136"><span class="cl-8167eba6">18.75</span></p></td>
<td class="cl-816cda4f"><p class="cl-816cb136"><span class="cl-8167eba6">81.34</span></p></td>
<td class="cl-816cda4f"><p class="cl-816cb136"><span class="cl-8167eba6">53.75</span></p></td>
<td class="cl-816cda4f"><p class="cl-816cb136"><span class="cl-8167eba6">102.90</span></p></td>
<td class="cl-816cda4f"><p class="cl-816cb136"><span class="cl-8167eba6">18.75</span></p></td>
<td class="cl-816cda4f"><p class="cl-816cb136"><span class="cl-8167eba6">92.40</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-816cda4f"><p class="cl-816cb136"><span class="cl-8167eba6">21.25</span></p></td>
<td class="cl-816cda4f"><p class="cl-816cb136"><span class="cl-8167eba6">115.36</span></p></td>
<td class="cl-816cda4f"><p class="cl-816cb136"><span class="cl-8167eba6">38.75</span></p></td>
<td class="cl-816cda4f"><p class="cl-816cb136"><span class="cl-8167eba6">91.70</span></p></td>
<td class="cl-816cda4f"><p class="cl-816cb136"><span class="cl-8167eba6">52.50</span></p></td>
<td class="cl-816cda4f"><p class="cl-816cb136"><span class="cl-8167eba6">110.74</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-816cda4f"><p class="cl-816cb136"><span class="cl-8167eba6"></span></p></td>
<td class="cl-816cda4f"><p class="cl-816cb136"><span class="cl-8167eba6"></span></p></td>
<td class="cl-816cda4f"><p class="cl-816cb136"><span class="cl-8167eba6">22.50</span></p></td>
<td class="cl-816cda4f"><p class="cl-816cb136"><span class="cl-8167eba6">102.76</span></p></td>
<td class="cl-816cda4f"><p class="cl-816cb136"><span class="cl-8167eba6">32.50</span></p></td>
<td class="cl-816cda4f"><p class="cl-816cb136"><span class="cl-8167eba6">105.70</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-816cda4f"><p class="cl-816cb136"><span class="cl-8167eba6"></span></p></td>
<td class="cl-816cda4f"><p class="cl-816cb136"><span class="cl-8167eba6"></span></p></td>
<td class="cl-816cda4f"><p class="cl-816cb136"><span class="cl-8167eba6">17.50</span></p></td>
<td class="cl-816cda4f"><p class="cl-816cb136"><span class="cl-8167eba6">78.54</span></p></td>
<td class="cl-816cda4f"><p class="cl-816cb136"><span class="cl-8167eba6"></span></p></td>
<td class="cl-816cda4f"><p class="cl-816cb136"><span class="cl-8167eba6"></span></p></td>
</tr>
</tbody>
</table></div>
</div>
<ol style="list-style-type: lower-alpha">
<li><p>Plot the given data as a single scatterplot that distinguishes between the three varieties.</p></li>
<li><p>What hypotheses and models are of importance when considering a covariance analysis of the given data?</p></li>
<li><p>Perform a detailed one-way ANCOVA.</p></li>
<li><p>Obtain estimates for the regression coefficients in the regression equations.</p></li>
</ol>
<p><span class="math display">\[
Y_{ij} = \mu + \beta x_{ij} + \epsilon_{ij}, \hspace{1cm} i = 1, 2, \dots, k; j = 1, 2, \dots, n_i
\]</span></p>
<p><span class="math display">\[
Y_{ij} = \mu + \beta_i x_{ij} + \epsilon_{ij}, \hspace{1cm} i = 1, 2, \dots, k; j = 1, 2, \dots, n_i
\]</span></p>
<ol start="5" style="list-style-type: lower-alpha">
<li>Interpret the results of the analysis of covariance using the output of <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code>.</li>
</ol>
</div>
</div>
<div id="heart-rate-exercise" class="section level3" number="12.14.5">
<h3>
<span class="header-section-number">12.14.5</span> Heart rate Exercise<a class="anchor" aria-label="anchor" href="#heart-rate-exercise"><i class="fas fa-link"></i></a>
</h3>
<div style="color: #80CC99;">
<p><span class="citation">Milliken &amp; Johnson (<a href="references.html#ref-MillikenJohnson2002">2002</a>)</span> discuss an investigation by a sport physiologist of the effect of three exercise programs (EX1, EX2 and EX3) on heart rate (HR) of males between 28 and 35 years of age. The experiment consists of the random allocation of a subject to one of the programs. The subject then had to follow the exercise program for 8 weeks. On finishing the program each subject had to complete a 6 minutes run and then had his heart rate (EHR) measured. As a measure of their fitness before entering the experiment each subject had also his resting heart rate (AHR) determined prior to the experiment. The following data were obtained:</p>
<div class="tabwid">
<style>.cl-81c3504a{}.cl-81959ace{font-family:'Arial';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(102, 102, 102, 1.00);background-color:transparent;}.cl-81a12d58{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:3pt;padding-top:3pt;padding-left:3pt;padding-right:3pt;line-height: 1;background-color:transparent;}.cl-81a12d6c{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:3pt;padding-top:3pt;padding-left:3pt;padding-right:3pt;line-height: 1;background-color:transparent;}.cl-81a2d180{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-81a2d216{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-81a2d220{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style>
<div class="inline-table"><table data-quarto-disable-processing="true" class="cl-81c3504a">
<thead>
<tr style="overflow-wrap:break-word;"><th colspan="6" class="cl-81a2d180"><p class="cl-81a12d58"><span class="cl-81959ace">EXERCISE PROGRAM</span></p></th></tr>
<tr style="overflow-wrap:break-word;">
<th colspan="2" class="cl-81a2d180"><p class="cl-81a12d58"><span class="cl-81959ace">EX1</span></p></th>
<th colspan="2" class="cl-81a2d180"><p class="cl-81a12d58"><span class="cl-81959ace">EX2</span></p></th>
<th colspan="2" class="cl-81a2d180"><p class="cl-81a12d58"><span class="cl-81959ace">EX3</span></p></th>
</tr>
<tr style="overflow-wrap:break-word;">
<th class="cl-81a2d216"><p class="cl-81a12d58"><span class="cl-81959ace">HER</span></p></th>
<th class="cl-81a2d216"><p class="cl-81a12d58"><span class="cl-81959ace">AHR</span></p></th>
<th class="cl-81a2d216"><p class="cl-81a12d58"><span class="cl-81959ace">HER</span></p></th>
<th class="cl-81a2d216"><p class="cl-81a12d58"><span class="cl-81959ace">AHR</span></p></th>
<th class="cl-81a2d216"><p class="cl-81a12d58"><span class="cl-81959ace">HER</span></p></th>
<th class="cl-81a2d216"><p class="cl-81a12d58"><span class="cl-81959ace">AHR</span></p></th>
</tr>
</thead>
<tbody>
<tr style="overflow-wrap:break-word;">
<td class="cl-81a2d220"><p class="cl-81a12d6c"><span class="cl-81959ace">118</span></p></td>
<td class="cl-81a2d220"><p class="cl-81a12d6c"><span class="cl-81959ace">56</span></p></td>
<td class="cl-81a2d220"><p class="cl-81a12d6c"><span class="cl-81959ace">148</span></p></td>
<td class="cl-81a2d220"><p class="cl-81a12d6c"><span class="cl-81959ace">60</span></p></td>
<td class="cl-81a2d220"><p class="cl-81a12d6c"><span class="cl-81959ace">153</span></p></td>
<td class="cl-81a2d220"><p class="cl-81a12d6c"><span class="cl-81959ace">56</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-81a2d220"><p class="cl-81a12d6c"><span class="cl-81959ace">138</span></p></td>
<td class="cl-81a2d220"><p class="cl-81a12d6c"><span class="cl-81959ace">59</span></p></td>
<td class="cl-81a2d220"><p class="cl-81a12d6c"><span class="cl-81959ace">159</span></p></td>
<td class="cl-81a2d220"><p class="cl-81a12d6c"><span class="cl-81959ace">62</span></p></td>
<td class="cl-81a2d220"><p class="cl-81a12d6c"><span class="cl-81959ace">150</span></p></td>
<td class="cl-81a2d220"><p class="cl-81a12d6c"><span class="cl-81959ace">58</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-81a2d220"><p class="cl-81a12d6c"><span class="cl-81959ace">142</span></p></td>
<td class="cl-81a2d220"><p class="cl-81a12d6c"><span class="cl-81959ace">62</span></p></td>
<td class="cl-81a2d220"><p class="cl-81a12d6c"><span class="cl-81959ace">162</span></p></td>
<td class="cl-81a2d220"><p class="cl-81a12d6c"><span class="cl-81959ace">65</span></p></td>
<td class="cl-81a2d220"><p class="cl-81a12d6c"><span class="cl-81959ace">158</span></p></td>
<td class="cl-81a2d220"><p class="cl-81a12d6c"><span class="cl-81959ace">61</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-81a2d220"><p class="cl-81a12d6c"><span class="cl-81959ace">147</span></p></td>
<td class="cl-81a2d220"><p class="cl-81a12d6c"><span class="cl-81959ace">68</span></p></td>
<td class="cl-81a2d220"><p class="cl-81a12d6c"><span class="cl-81959ace">157</span></p></td>
<td class="cl-81a2d220"><p class="cl-81a12d6c"><span class="cl-81959ace">66</span></p></td>
<td class="cl-81a2d220"><p class="cl-81a12d6c"><span class="cl-81959ace">152</span></p></td>
<td class="cl-81a2d220"><p class="cl-81a12d6c"><span class="cl-81959ace">64</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-81a2d220"><p class="cl-81a12d6c"><span class="cl-81959ace">160</span></p></td>
<td class="cl-81a2d220"><p class="cl-81a12d6c"><span class="cl-81959ace">71</span></p></td>
<td class="cl-81a2d220"><p class="cl-81a12d6c"><span class="cl-81959ace">169</span></p></td>
<td class="cl-81a2d220"><p class="cl-81a12d6c"><span class="cl-81959ace">73</span></p></td>
<td class="cl-81a2d220"><p class="cl-81a12d6c"><span class="cl-81959ace">160</span></p></td>
<td class="cl-81a2d220"><p class="cl-81a12d6c"><span class="cl-81959ace">72</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-81a2d220"><p class="cl-81a12d6c"><span class="cl-81959ace">166</span></p></td>
<td class="cl-81a2d220"><p class="cl-81a12d6c"><span class="cl-81959ace">76</span></p></td>
<td class="cl-81a2d220"><p class="cl-81a12d6c"><span class="cl-81959ace">164</span></p></td>
<td class="cl-81a2d220"><p class="cl-81a12d6c"><span class="cl-81959ace">75</span></p></td>
<td class="cl-81a2d220"><p class="cl-81a12d6c"><span class="cl-81959ace">154</span></p></td>
<td class="cl-81a2d220"><p class="cl-81a12d6c"><span class="cl-81959ace">75</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-81a2d220"><p class="cl-81a12d6c"><span class="cl-81959ace">165</span></p></td>
<td class="cl-81a2d220"><p class="cl-81a12d6c"><span class="cl-81959ace">83</span></p></td>
<td class="cl-81a2d220"><p class="cl-81a12d6c"><span class="cl-81959ace">179</span></p></td>
<td class="cl-81a2d220"><p class="cl-81a12d6c"><span class="cl-81959ace">84</span></p></td>
<td class="cl-81a2d220"><p class="cl-81a12d6c"><span class="cl-81959ace">155</span></p></td>
<td class="cl-81a2d220"><p class="cl-81a12d6c"><span class="cl-81959ace">82</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-81a2d220"><p class="cl-81a12d6c"><span class="cl-81959ace">171</span></p></td>
<td class="cl-81a2d220"><p class="cl-81a12d6c"><span class="cl-81959ace">87</span></p></td>
<td class="cl-81a2d220"><p class="cl-81a12d6c"><span class="cl-81959ace">177</span></p></td>
<td class="cl-81a2d220"><p class="cl-81a12d6c"><span class="cl-81959ace">88</span></p></td>
<td class="cl-81a2d220"><p class="cl-81a12d6c"><span class="cl-81959ace">164</span></p></td>
<td class="cl-81a2d220"><p class="cl-81a12d6c"><span class="cl-81959ace">86</span></p></td>
</tr>
</tbody>
</table></div>
</div>
<p>Analyze the data and discuss the results.</p>
</div>

</div>
</div>
</div>
  <div class="chapter-nav">
<div class="empty"></div>
<div class="empty"></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <div id="book-on-this-page"></div>

      <div class="book-extra">
        <ul class="list-unstyled">
          
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>Introduction into R Applications and Programming: A Tutorial</strong>" was written by Niël J le Roux and Sugnet Lubbe. It was last built on 2025.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
